// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ads.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAd = `-- name: CreateAd :one
INSERT INTO ads (name, video_url, click_url, weight, starts_at, ends_at, enabled,
                 state_id, sublocation_id, video_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING ad_id, name, video_url, click_url, weight, starts_at, ends_at, enabled, state_id, sublocation_id, video_id, created_by, created_at, updated_at
`

type CreateAdParams struct {
	Name          string             `json:"name"`
	VideoUrl      string             `json:"video_url"`
	ClickUrl      string             `json:"click_url"`
	Weight        int32              `json:"weight"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Enabled       bool               `json:"enabled"`
	StateID       *int32             `json:"state_id"`
	SublocationID *int32             `json:"sublocation_id"`
	VideoID       *int32             `json:"video_id"`
	CreatedBy     string             `json:"created_by"`
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error) {
	row := q.db.QueryRow(ctx, createAd,
		arg.Name,
		arg.VideoUrl,
		arg.ClickUrl,
		arg.Weight,
		arg.StartsAt,
		arg.EndsAt,
		arg.Enabled,
		arg.StateID,
		arg.SublocationID,
		arg.VideoID,
		arg.CreatedBy,
	)
	var i Ad
	err := row.Scan(
		&i.AdID,
		&i.Name,
		&i.VideoUrl,
		&i.ClickUrl,
		&i.Weight,
		&i.StartsAt,
		&i.EndsAt,
		&i.Enabled,
		&i.StateID,
		&i.SublocationID,
		&i.VideoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAd = `-- name: DeleteAd :exec
DELETE FROM ads WHERE ad_id = $1
`

func (q *Queries) DeleteAd(ctx context.Context, adID int32) error {
	_, err := q.db.Exec(ctx, deleteAd, adID)
	return err
}

const getAd = `-- name: GetAd :one
SELECT ad_id, name, video_url, click_url, weight, starts_at, ends_at, enabled, state_id, sublocation_id, video_id, created_by, created_at, updated_at FROM ads WHERE ad_id = $1
`

func (q *Queries) GetAd(ctx context.Context, adID int32) (Ad, error) {
	row := q.db.QueryRow(ctx, getAd, adID)
	var i Ad
	err := row.Scan(
		&i.AdID,
		&i.Name,
		&i.VideoUrl,
		&i.ClickUrl,
		&i.Weight,
		&i.StartsAt,
		&i.EndsAt,
		&i.Enabled,
		&i.StateID,
		&i.SublocationID,
		&i.VideoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAds = `-- name: ListAds :many
SELECT a.ad_id, a.name, a.video_url, a.click_url, a.weight, a.starts_at, a.ends_at,
       a.enabled, a.state_id, a.sublocation_id, a.video_id, a.created_by,
       a.created_at, a.updated_at,
       COALESCE(st.name, '') AS state_name,
       COALESCE(sub.name, '') AS sublocation_name,
       COALESCE(v.title, '') AS video_title,
       COUNT(i.impression_id) FILTER (WHERE i.kind = 'impression') AS impressions,
       COUNT(i.impression_id) FILTER (WHERE i.kind = 'click') AS clicks
FROM ads a
LEFT JOIN states st ON st.state_id = a.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = a.sublocation_id
LEFT JOIN videos v ON v.video_id = a.video_id
LEFT JOIN ad_impressions i ON i.ad_id = a.ad_id
GROUP BY a.ad_id, st.name, sub.name, v.title
ORDER BY a.ad_id
`

type ListAdsRow struct {
	AdID            int32              `json:"ad_id"`
	Name            string             `json:"name"`
	VideoUrl        string             `json:"video_url"`
	ClickUrl        string             `json:"click_url"`
	Weight          int32              `json:"weight"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	Enabled         bool               `json:"enabled"`
	StateID         *int32             `json:"state_id"`
	SublocationID   *int32             `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	StateName       string             `json:"state_name"`
	SublocationName string             `json:"sublocation_name"`
	VideoTitle      string             `json:"video_title"`
	Impressions     int64              `json:"impressions"`
	Clicks          int64              `json:"clicks"`
}

// ListAds backs the admin dashboard and doubles as the billing report — lifetime
// impression and click counts come straight off ad_impressions.
func (q *Queries) ListAds(ctx context.Context) ([]ListAdsRow, error) {
	rows, err := q.db.Query(ctx, listAds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdsRow{}
	for rows.Next() {
		var i ListAdsRow
		if err := rows.Scan(
			&i.AdID,
			&i.Name,
			&i.VideoUrl,
			&i.ClickUrl,
			&i.Weight,
			&i.StartsAt,
			&i.EndsAt,
			&i.Enabled,
			&i.StateID,
			&i.SublocationID,
			&i.VideoID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
			&i.VideoTitle,
			&i.Impressions,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdEvent = `-- name: RecordAdEvent :exec
INSERT INTO ad_impressions (ad_id, video_id, kind) VALUES ($1, $2, $3)
`

type RecordAdEventParams struct {
	AdID    int32  `json:"ad_id"`
	VideoID *int32 `json:"video_id"`
	Kind    string `json:"kind"`
}

// RecordAdEvent appends one impression or click. One row per delivered ad, written
// synchronously so the caller learns if it failed and can retry.
func (q *Queries) RecordAdEvent(ctx context.Context, arg RecordAdEventParams) error {
	_, err := q.db.Exec(ctx, recordAdEvent, arg.AdID, arg.VideoID, arg.Kind)
	return err
}

const resolveAdCandidates = `-- name: ResolveAdCandidates :many
WITH cam AS (
  SELECT v.video_id, v.state_id, v.sublocation_id FROM videos v WHERE v.video_id = $1
), eligible AS (
  SELECT a.ad_id, a.name, a.video_url, a.click_url, a.weight, a.starts_at, a.ends_at,
         (CASE
            WHEN a.video_id IS NOT NULL THEN 3
            WHEN a.sublocation_id IS NOT NULL THEN 2
            WHEN a.state_id IS NOT NULL THEN 1
            ELSE 0
          END)::int AS scope
  FROM ads a
  JOIN cam ON a.video_id = cam.video_id
           OR a.sublocation_id = cam.sublocation_id
           OR a.state_id = cam.state_id
           OR num_nonnulls(a.state_id, a.sublocation_id, a.video_id) = 0
  WHERE a.enabled
    AND (a.starts_at IS NULL OR a.starts_at <= now())
    AND (a.ends_at IS NULL OR a.ends_at > now())
)
SELECT ad_id, name, video_url, click_url, weight, starts_at, ends_at, scope
FROM eligible
WHERE scope = (SELECT max(scope) FROM eligible)
ORDER BY ad_id
`

type ResolveAdCandidatesRow struct {
	AdID     int32              `json:"ad_id"`
	Name     string             `json:"name"`
	VideoUrl string             `json:"video_url"`
	ClickUrl string             `json:"click_url"`
	Weight   int32              `json:"weight"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	Scope    int32              `json:"scope"`
}

// ResolveAdCandidates implements most-specific-wins targeting for one camera.
// It collects every ad eligible for that camera (right scope, enabled, inside its
// active window), tags each with a scope rank, and returns only the rows at the
// highest rank present: camera (3) → sublocation (2) → state (1) → global (0).
// No eligible ad at any level returns no rows.
//
// It returns the whole winning level rather than one winner so the caller can
// cache the level and still roll a fresh weighted pick on every request.
func (q *Queries) ResolveAdCandidates(ctx context.Context, videoID int32) ([]ResolveAdCandidatesRow, error) {
	rows, err := q.db.Query(ctx, resolveAdCandidates, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveAdCandidatesRow{}
	for rows.Next() {
		var i ResolveAdCandidatesRow
		if err := rows.Scan(
			&i.AdID,
			&i.Name,
			&i.VideoUrl,
			&i.ClickUrl,
			&i.Weight,
			&i.StartsAt,
			&i.EndsAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAd = `-- name: UpdateAd :one
UPDATE ads SET name = $2, video_url = $3, click_url = $4, weight = $5,
               starts_at = $6, ends_at = $7, enabled = $8,
               state_id = $9, sublocation_id = $10, video_id = $11
WHERE ad_id = $1
RETURNING ad_id, name, video_url, click_url, weight, starts_at, ends_at, enabled, state_id, sublocation_id, video_id, created_by, created_at, updated_at
`

type UpdateAdParams struct {
	AdID          int32              `json:"ad_id"`
	Name          string             `json:"name"`
	VideoUrl      string             `json:"video_url"`
	ClickUrl      string             `json:"click_url"`
	Weight        int32              `json:"weight"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Enabled       bool               `json:"enabled"`
	StateID       *int32             `json:"state_id"`
	SublocationID *int32             `json:"sublocation_id"`
	VideoID       *int32             `json:"video_id"`
}

func (q *Queries) UpdateAd(ctx context.Context, arg UpdateAdParams) (Ad, error) {
	row := q.db.QueryRow(ctx, updateAd,
		arg.AdID,
		arg.Name,
		arg.VideoUrl,
		arg.ClickUrl,
		arg.Weight,
		arg.StartsAt,
		arg.EndsAt,
		arg.Enabled,
		arg.StateID,
		arg.SublocationID,
		arg.VideoID,
	)
	var i Ad
	err := row.Scan(
		&i.AdID,
		&i.Name,
		&i.VideoUrl,
		&i.ClickUrl,
		&i.Weight,
		&i.StartsAt,
		&i.EndsAt,
		&i.Enabled,
		&i.StateID,
		&i.SublocationID,
		&i.VideoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
