// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: audio_stations.sql

package db

import (
	"context"
	"time"
)

const createAudioStation = `-- name: CreateAudioStation :one
INSERT INTO audio_stations (name, stream_url, enabled, sort_order, state_id, sublocation_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING audio_station_id, name, stream_url, enabled, sort_order, state_id, sublocation_id, created_at, updated_at
`

type CreateAudioStationParams struct {
	Name          string `json:"name"`
	StreamUrl     string `json:"stream_url"`
	Enabled       bool   `json:"enabled"`
	SortOrder     int32  `json:"sort_order"`
	StateID       *int32 `json:"state_id"`
	SublocationID *int32 `json:"sublocation_id"`
}

func (q *Queries) CreateAudioStation(ctx context.Context, arg CreateAudioStationParams) (AudioStation, error) {
	row := q.db.QueryRow(ctx, createAudioStation,
		arg.Name,
		arg.StreamUrl,
		arg.Enabled,
		arg.SortOrder,
		arg.StateID,
		arg.SublocationID,
	)
	var i AudioStation
	err := row.Scan(
		&i.AudioStationID,
		&i.Name,
		&i.StreamUrl,
		&i.Enabled,
		&i.SortOrder,
		&i.StateID,
		&i.SublocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAudioStation = `-- name: DeleteAudioStation :exec
DELETE FROM audio_stations WHERE audio_station_id = $1
`

func (q *Queries) DeleteAudioStation(ctx context.Context, audioStationID int32) error {
	_, err := q.db.Exec(ctx, deleteAudioStation, audioStationID)
	return err
}

const listAudioStations = `-- name: ListAudioStations :many

SELECT a.audio_station_id, a.name, a.stream_url, a.enabled, a.sort_order,
       a.state_id, a.sublocation_id, a.created_at, a.updated_at,
       COALESCE(st.name, '') AS state_name,
       COALESCE(sub.name, '') AS sublocation_name
FROM audio_stations a
LEFT JOIN states st ON st.state_id = a.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = a.sublocation_id
ORDER BY a.sort_order, a.name
`

type ListAudioStationsRow struct {
	AudioStationID  int32     `json:"audio_station_id"`
	Name            string    `json:"name"`
	StreamUrl       string    `json:"stream_url"`
	Enabled         bool      `json:"enabled"`
	SortOrder       int32     `json:"sort_order"`
	StateID         *int32    `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	SublocationName string    `json:"sublocation_name"`
}

// Audio stations (DAN-47) — admin-managed radio stations merged with the
// AzuraCast list at GET /audio/stations. Scope is optional and single-level:
// NULL/NULL is sitewide, state_id or sublocation_id narrows it. There is no
// per-camera scope.
// Every station for the admin panel, with the scope's display name joined in.
func (q *Queries) ListAudioStations(ctx context.Context) ([]ListAudioStationsRow, error) {
	rows, err := q.db.Query(ctx, listAudioStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAudioStationsRow{}
	for rows.Next() {
		var i ListAudioStationsRow
		if err := rows.Scan(
			&i.AudioStationID,
			&i.Name,
			&i.StreamUrl,
			&i.Enabled,
			&i.SortOrder,
			&i.StateID,
			&i.SublocationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicAudioStations = `-- name: ListPublicAudioStations :many
WITH ctx AS (
  SELECT state_id AS ctx_state, sublocation_id AS ctx_sub
  FROM videos WHERE video_id = $1::int
)
SELECT a.audio_station_id, a.name, a.stream_url
FROM audio_stations a
LEFT JOIN ctx ON true
WHERE a.enabled
  AND (
    (a.state_id IS NULL AND a.sublocation_id IS NULL)
    OR a.state_id = ctx.ctx_state
    OR a.sublocation_id = ctx.ctx_sub
  )
ORDER BY a.sort_order, a.name
`

type ListPublicAudioStationsRow struct {
	AudioStationID int32  `json:"audio_station_id"`
	Name           string `json:"name"`
	StreamUrl      string `json:"stream_url"`
}

// ListPublicAudioStations resolves the camera's own state/sublocation (if any)
// through the ctx CTE and returns every enabled station that is unscoped or
// matches. When video_id is omitted (or unknown), ctx has no row, so only
// unscoped stations match.
func (q *Queries) ListPublicAudioStations(ctx context.Context, videoID *int32) ([]ListPublicAudioStationsRow, error) {
	rows, err := q.db.Query(ctx, listPublicAudioStations, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicAudioStationsRow{}
	for rows.Next() {
		var i ListPublicAudioStationsRow
		if err := rows.Scan(&i.AudioStationID, &i.Name, &i.StreamUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAudioStation = `-- name: UpdateAudioStation :one
UPDATE audio_stations
SET name = $2, stream_url = $3, enabled = $4, sort_order = $5,
    state_id = $6, sublocation_id = $7
WHERE audio_station_id = $1
RETURNING audio_station_id, name, stream_url, enabled, sort_order, state_id, sublocation_id, created_at, updated_at
`

type UpdateAudioStationParams struct {
	AudioStationID int32  `json:"audio_station_id"`
	Name           string `json:"name"`
	StreamUrl      string `json:"stream_url"`
	Enabled        bool   `json:"enabled"`
	SortOrder      int32  `json:"sort_order"`
	StateID        *int32 `json:"state_id"`
	SublocationID  *int32 `json:"sublocation_id"`
}

func (q *Queries) UpdateAudioStation(ctx context.Context, arg UpdateAudioStationParams) (AudioStation, error) {
	row := q.db.QueryRow(ctx, updateAudioStation,
		arg.AudioStationID,
		arg.Name,
		arg.StreamUrl,
		arg.Enabled,
		arg.SortOrder,
		arg.StateID,
		arg.SublocationID,
	)
	var i AudioStation
	err := row.Scan(
		&i.AudioStationID,
		&i.Name,
		&i.StreamUrl,
		&i.Enabled,
		&i.SortOrder,
		&i.StateID,
		&i.SublocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
