// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, description_md, starts_at, ends_at, url, sublocation_id, video_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING event_id, title, description_md, starts_at, ends_at, url, sublocation_id, video_id, created_by, created_at, updated_at
`

type CreateEventParams struct {
	Title         string             `json:"title"`
	DescriptionMd string             `json:"description_md"`
	StartsAt      time.Time          `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Url           pgtype.Text        `json:"url"`
	SublocationID int32              `json:"sublocation_id"`
	VideoID       *int32             `json:"video_id"`
	CreatedBy     string             `json:"created_by"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.DescriptionMd,
		arg.StartsAt,
		arg.EndsAt,
		arg.Url,
		arg.SublocationID,
		arg.VideoID,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.Title,
		&i.DescriptionMd,
		&i.StartsAt,
		&i.EndsAt,
		&i.Url,
		&i.SublocationID,
		&i.VideoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE event_id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, eventID int32) error {
	_, err := q.db.Exec(ctx, deleteEvent, eventID)
	return err
}

const getEvent = `-- name: GetEvent :one

SELECT event_id, title, description_md, starts_at, ends_at, url, sublocation_id, video_id, created_by, created_at, updated_at FROM events WHERE event_id = $1
`

// Events queries.
//
// Unlike ads/posts, sublocation_id is required (an event always belongs to
// one place) and video_id is an optional, additional "watch here" pointer to
// a specific camera within that sublocation — the handler checks the two
// agree before writing. Every listing here joins the sublocation and its
// parent state so the frontend can link straight to the camera/sublocation
// page without a second round trip.
func (q *Queries) GetEvent(ctx context.Context, eventID int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, eventID)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.Title,
		&i.DescriptionMd,
		&i.StartsAt,
		&i.EndsAt,
		&i.Url,
		&i.SublocationID,
		&i.VideoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT e.event_id, e.title, e.description_md, e.starts_at, e.ends_at, e.url,
       e.sublocation_id, e.video_id, e.created_by, e.created_at, e.updated_at,
       sub.name AS sublocation_name, sub.slug AS sublocation_slug,
       st.name AS state_name, st.slug AS state_slug,
       COALESCE(v.title, '') AS video_title, COALESCE(v.slug, '') AS video_slug
FROM events e
JOIN sublocations sub ON sub.sublocation_id = e.sublocation_id
JOIN states st ON st.state_id = sub.state_id
LEFT JOIN videos v ON v.video_id = e.video_id
ORDER BY e.starts_at DESC
`

type ListAllEventsRow struct {
	EventID         int32              `json:"event_id"`
	Title           string             `json:"title"`
	DescriptionMd   string             `json:"description_md"`
	StartsAt        time.Time          `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	Url             pgtype.Text        `json:"url"`
	SublocationID   int32              `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	SublocationName string             `json:"sublocation_name"`
	SublocationSlug string             `json:"sublocation_slug"`
	StateName       string             `json:"state_name"`
	StateSlug       string             `json:"state_slug"`
	VideoTitle      string             `json:"video_title"`
	VideoSlug       string             `json:"video_slug"`
}

// ListAllEvents backs the admin dashboard — every event regardless of
// whether it's upcoming or past, newest starts_at first.
func (q *Queries) ListAllEvents(ctx context.Context) ([]ListAllEventsRow, error) {
	rows, err := q.db.Query(ctx, listAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllEventsRow{}
	for rows.Next() {
		var i ListAllEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.DescriptionMd,
			&i.StartsAt,
			&i.EndsAt,
			&i.Url,
			&i.SublocationID,
			&i.VideoID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SublocationName,
			&i.SublocationSlug,
			&i.StateName,
			&i.StateSlug,
			&i.VideoTitle,
			&i.VideoSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT e.event_id, e.title, e.description_md, e.starts_at, e.ends_at, e.url,
       e.sublocation_id, e.video_id, e.created_by, e.created_at, e.updated_at,
       sub.name AS sublocation_name, sub.slug AS sublocation_slug,
       st.name AS state_name, st.slug AS state_slug,
       COALESCE(v.title, '') AS video_title, COALESCE(v.slug, '') AS video_slug
FROM events e
JOIN sublocations sub ON sub.sublocation_id = e.sublocation_id
JOIN states st ON st.state_id = sub.state_id
LEFT JOIN videos v ON v.video_id = e.video_id
WHERE COALESCE(e.ends_at, e.starts_at) >= now()
ORDER BY e.starts_at ASC
LIMIT 50
`

type ListUpcomingEventsRow struct {
	EventID         int32              `json:"event_id"`
	Title           string             `json:"title"`
	DescriptionMd   string             `json:"description_md"`
	StartsAt        time.Time          `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	Url             pgtype.Text        `json:"url"`
	SublocationID   int32              `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	SublocationName string             `json:"sublocation_name"`
	SublocationSlug string             `json:"sublocation_slug"`
	StateName       string             `json:"state_name"`
	StateSlug       string             `json:"state_slug"`
	VideoTitle      string             `json:"video_title"`
	VideoSlug       string             `json:"video_slug"`
}

// ListUpcomingEvents backs GET /events?upcoming=1 (the sitewide /events page)
// — every event across every sublocation, soonest first. An event counts as
// "upcoming" until it ends (or, with no end time, until it starts), so an
// event already in progress still shows.
func (q *Queries) ListUpcomingEvents(ctx context.Context) ([]ListUpcomingEventsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsRow{}
	for rows.Next() {
		var i ListUpcomingEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.DescriptionMd,
			&i.StartsAt,
			&i.EndsAt,
			&i.Url,
			&i.SublocationID,
			&i.VideoID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SublocationName,
			&i.SublocationSlug,
			&i.StateName,
			&i.StateSlug,
			&i.VideoTitle,
			&i.VideoSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEventsBySublocation = `-- name: ListUpcomingEventsBySublocation :many

SELECT e.event_id, e.title, e.description_md, e.starts_at, e.ends_at, e.url,
       e.sublocation_id, e.video_id, e.created_by, e.created_at, e.updated_at,
       sub.name AS sublocation_name, sub.slug AS sublocation_slug,
       st.name AS state_name, st.slug AS state_slug,
       COALESCE(v.title, '') AS video_title, COALESCE(v.slug, '') AS video_slug
FROM events e
JOIN sublocations sub ON sub.sublocation_id = e.sublocation_id
JOIN states st ON st.state_id = sub.state_id
LEFT JOIN videos v ON v.video_id = e.video_id
WHERE e.sublocation_id = $1 AND COALESCE(e.ends_at, e.starts_at) >= now()
ORDER BY e.starts_at ASC
LIMIT $2
`

type ListUpcomingEventsBySublocationParams struct {
	SublocationID int32 `json:"sublocation_id"`
	Limit         int32 `json:"limit"`
}

type ListUpcomingEventsBySublocationRow struct {
	EventID         int32              `json:"event_id"`
	Title           string             `json:"title"`
	DescriptionMd   string             `json:"description_md"`
	StartsAt        time.Time          `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	Url             pgtype.Text        `json:"url"`
	SublocationID   int32              `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	SublocationName string             `json:"sublocation_name"`
	SublocationSlug string             `json:"sublocation_slug"`
	StateName       string             `json:"state_name"`
	StateSlug       string             `json:"state_slug"`
	VideoTitle      string             `json:"video_title"`
	VideoSlug       string             `json:"video_slug"`
}

// ListUpcomingEventsBySublocation and ListUpcomingEventsByVideo back the
// "Upcoming" block on a sublocation/camera page (limit 3) — same upcoming
// filter and ordering as ListUpcomingEvents, scoped to one place/camera.
func (q *Queries) ListUpcomingEventsBySublocation(ctx context.Context, arg ListUpcomingEventsBySublocationParams) ([]ListUpcomingEventsBySublocationRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEventsBySublocation, arg.SublocationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsBySublocationRow{}
	for rows.Next() {
		var i ListUpcomingEventsBySublocationRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.DescriptionMd,
			&i.StartsAt,
			&i.EndsAt,
			&i.Url,
			&i.SublocationID,
			&i.VideoID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SublocationName,
			&i.SublocationSlug,
			&i.StateName,
			&i.StateSlug,
			&i.VideoTitle,
			&i.VideoSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEventsByVideo = `-- name: ListUpcomingEventsByVideo :many
SELECT e.event_id, e.title, e.description_md, e.starts_at, e.ends_at, e.url,
       e.sublocation_id, e.video_id, e.created_by, e.created_at, e.updated_at,
       sub.name AS sublocation_name, sub.slug AS sublocation_slug,
       st.name AS state_name, st.slug AS state_slug,
       COALESCE(v.title, '') AS video_title, COALESCE(v.slug, '') AS video_slug
FROM events e
JOIN sublocations sub ON sub.sublocation_id = e.sublocation_id
JOIN states st ON st.state_id = sub.state_id
LEFT JOIN videos v ON v.video_id = e.video_id
WHERE e.video_id = $1 AND COALESCE(e.ends_at, e.starts_at) >= now()
ORDER BY e.starts_at ASC
LIMIT $2
`

type ListUpcomingEventsByVideoParams struct {
	VideoID *int32 `json:"video_id"`
	Limit   int32  `json:"limit"`
}

type ListUpcomingEventsByVideoRow struct {
	EventID         int32              `json:"event_id"`
	Title           string             `json:"title"`
	DescriptionMd   string             `json:"description_md"`
	StartsAt        time.Time          `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	Url             pgtype.Text        `json:"url"`
	SublocationID   int32              `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	SublocationName string             `json:"sublocation_name"`
	SublocationSlug string             `json:"sublocation_slug"`
	StateName       string             `json:"state_name"`
	StateSlug       string             `json:"state_slug"`
	VideoTitle      string             `json:"video_title"`
	VideoSlug       string             `json:"video_slug"`
}

func (q *Queries) ListUpcomingEventsByVideo(ctx context.Context, arg ListUpcomingEventsByVideoParams) ([]ListUpcomingEventsByVideoRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEventsByVideo, arg.VideoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingEventsByVideoRow{}
	for rows.Next() {
		var i ListUpcomingEventsByVideoRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.DescriptionMd,
			&i.StartsAt,
			&i.EndsAt,
			&i.Url,
			&i.SublocationID,
			&i.VideoID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SublocationName,
			&i.SublocationSlug,
			&i.StateName,
			&i.StateSlug,
			&i.VideoTitle,
			&i.VideoSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET title = $2, description_md = $3, starts_at = $4, ends_at = $5,
                  url = $6, sublocation_id = $7, video_id = $8
WHERE event_id = $1
RETURNING event_id, title, description_md, starts_at, ends_at, url, sublocation_id, video_id, created_by, created_at, updated_at
`

type UpdateEventParams struct {
	EventID       int32              `json:"event_id"`
	Title         string             `json:"title"`
	DescriptionMd string             `json:"description_md"`
	StartsAt      time.Time          `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Url           pgtype.Text        `json:"url"`
	SublocationID int32              `json:"sublocation_id"`
	VideoID       *int32             `json:"video_id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.EventID,
		arg.Title,
		arg.DescriptionMd,
		arg.StartsAt,
		arg.EndsAt,
		arg.Url,
		arg.SublocationID,
		arg.VideoID,
	)
	var i Event
	err := row.Scan(
		&i.EventID,
		&i.Title,
		&i.DescriptionMd,
		&i.StartsAt,
		&i.EndsAt,
		&i.Url,
		&i.SublocationID,
		&i.VideoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
