// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: me.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnerSublocations = `-- name: CountOwnerSublocations :one

SELECT COUNT(*)::int FROM sublocations WHERE owner_id = $1
`

// Owner endpoints (DAN-39): everything under /me. Rows carry owner_id so the
// handler can enforce ownership (403 on someone else's row); the two
// Get*ForOwner queries take no owner filter on purpose so a foreign row is a
// 403, not a 404. Nothing here is Redis-cached (responses are per user).
func (q *Queries) CountOwnerSublocations(ctx context.Context, ownerID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOwnerSublocations, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwnerVideos = `-- name: CountOwnerVideos :one
SELECT COUNT(*)::int FROM videos WHERE owner_id = $1
`

func (q *Queries) CountOwnerVideos(ctx context.Context, ownerID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOwnerVideos, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwnerVideosSince = `-- name: CountOwnerVideosSince :one
SELECT COUNT(*)::int FROM videos WHERE owner_id = $1 AND created_at > $2
`

type CountOwnerVideosSinceParams struct {
	OwnerID   string    `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
}

// CountOwnerVideosSince backs the per-day creation limit. It counts rows that
// still exist, so a delete frees a slot; the limit is anti-abuse, not billing.
func (q *Queries) CountOwnerVideosSince(ctx context.Context, arg CountOwnerVideosSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOwnerVideosSince, arg.OwnerID, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countVideosInSublocation = `-- name: CountVideosInSublocation :one
SELECT COUNT(*)::int FROM videos WHERE sublocation_id = $1
`

func (q *Queries) CountVideosInSublocation(ctx context.Context, sublocationID *int32) (int32, error) {
	row := q.db.QueryRow(ctx, countVideosInSublocation, sublocationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createOwnerSublocation = `-- name: CreateOwnerSublocation :one
INSERT INTO sublocations (name, description, state_id, address, lat, lng, host_name, host_url, host_since, owner_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'pending')
RETURNING sublocation_id
`

type CreateOwnerSublocationParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	StateID     int32         `json:"state_id"`
	Address     string        `json:"address"`
	Lat         pgtype.Float8 `json:"lat"`
	Lng         pgtype.Float8 `json:"lng"`
	HostName    string        `json:"host_name"`
	HostUrl     string        `json:"host_url"`
	HostSince   pgtype.Date   `json:"host_since"`
	OwnerID     string        `json:"owner_id"`
}

func (q *Queries) CreateOwnerSublocation(ctx context.Context, arg CreateOwnerSublocationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOwnerSublocation,
		arg.Name,
		arg.Description,
		arg.StateID,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.HostName,
		arg.HostUrl,
		arg.HostSince,
		arg.OwnerID,
	)
	var sublocation_id int32
	err := row.Scan(&sublocation_id)
	return sublocation_id, err
}

const createOwnerVideo = `-- name: CreateOwnerVideo :one
INSERT INTO videos (title, src, type, state_id, sublocation_id, about, owner_id, stream_id, created_by, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending')
RETURNING video_id
`

type CreateOwnerVideoParams struct {
	Title         string      `json:"title"`
	Src           string      `json:"src"`
	Type          string      `json:"type"`
	StateID       int32       `json:"state_id"`
	SublocationID *int32      `json:"sublocation_id"`
	About         string      `json:"about"`
	OwnerID       string      `json:"owner_id"`
	StreamID      pgtype.Text `json:"stream_id"`
	CreatedBy     string      `json:"created_by"`
}

func (q *Queries) CreateOwnerVideo(ctx context.Context, arg CreateOwnerVideoParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOwnerVideo,
		arg.Title,
		arg.Src,
		arg.Type,
		arg.StateID,
		arg.SublocationID,
		arg.About,
		arg.OwnerID,
		arg.StreamID,
		arg.CreatedBy,
	)
	var video_id int32
	err := row.Scan(&video_id)
	return video_id, err
}

const getSublocationForOwner = `-- name: GetSublocationForOwner :one
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.status, sub.owner_id, sub.review_note,
       sub.lat, sub.lng, sub.host_name, sub.host_url, sub.host_since, sub.address,
       sub.created_at, sub.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id
WHERE sub.sublocation_id = $1
GROUP BY sub.sublocation_id, s.name, s.slug
`

type GetSublocationForOwnerRow struct {
	SublocationID int32         `json:"sublocation_id"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	StateID       int32         `json:"state_id"`
	Slug          string        `json:"slug"`
	Status        string        `json:"status"`
	OwnerID       string        `json:"owner_id"`
	ReviewNote    string        `json:"review_note"`
	Lat           pgtype.Float8 `json:"lat"`
	Lng           pgtype.Float8 `json:"lng"`
	HostName      string        `json:"host_name"`
	HostUrl       string        `json:"host_url"`
	HostSince     pgtype.Date   `json:"host_since"`
	Address       string        `json:"address"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
	StateName     string        `json:"state_name"`
	StateSlug     string        `json:"state_slug"`
	VideoCount    int32         `json:"video_count"`
}

func (q *Queries) GetSublocationForOwner(ctx context.Context, sublocationID int32) (GetSublocationForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getSublocationForOwner, sublocationID)
	var i GetSublocationForOwnerRow
	err := row.Scan(
		&i.SublocationID,
		&i.Name,
		&i.Description,
		&i.StateID,
		&i.Slug,
		&i.Status,
		&i.OwnerID,
		&i.ReviewNote,
		&i.Lat,
		&i.Lng,
		&i.HostName,
		&i.HostUrl,
		&i.HostSince,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.StateSlug,
		&i.VideoCount,
	)
	return i, err
}

const getVideoForOwner = `-- name: GetVideoForOwner :one
SELECT v.video_id, v.title, v.slug, v.src, v.type, v.state_id, v.sublocation_id,
       v.status, v.owner_id, v.stream_id, v.review_note, v.about,
       v.created_at, v.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COALESCE(sub.name, '') AS sublocation_name,
       COALESCE(sub.slug, '') AS sublocation_slug,
       COALESCE(sub.status, '') AS sublocation_status
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.video_id = $1
`

type GetVideoForOwnerRow struct {
	VideoID           int32       `json:"video_id"`
	Title             string      `json:"title"`
	Slug              string      `json:"slug"`
	Src               string      `json:"src"`
	Type              string      `json:"type"`
	StateID           int32       `json:"state_id"`
	SublocationID     *int32      `json:"sublocation_id"`
	Status            string      `json:"status"`
	OwnerID           string      `json:"owner_id"`
	StreamID          pgtype.Text `json:"stream_id"`
	ReviewNote        string      `json:"review_note"`
	About             string      `json:"about"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	StateName         string      `json:"state_name"`
	StateSlug         string      `json:"state_slug"`
	SublocationName   string      `json:"sublocation_name"`
	SublocationSlug   string      `json:"sublocation_slug"`
	SublocationStatus string      `json:"sublocation_status"`
}

func (q *Queries) GetVideoForOwner(ctx context.Context, videoID int32) (GetVideoForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getVideoForOwner, videoID)
	var i GetVideoForOwnerRow
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Slug,
		&i.Src,
		&i.Type,
		&i.StateID,
		&i.SublocationID,
		&i.Status,
		&i.OwnerID,
		&i.StreamID,
		&i.ReviewNote,
		&i.About,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.StateSlug,
		&i.SublocationName,
		&i.SublocationSlug,
		&i.SublocationStatus,
	)
	return i, err
}

const listOwnerSublocations = `-- name: ListOwnerSublocations :many
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.status, sub.owner_id, sub.review_note,
       sub.lat, sub.lng, sub.host_name, sub.host_url, sub.host_since, sub.address,
       sub.created_at, sub.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id
WHERE sub.owner_id = $1
GROUP BY sub.sublocation_id, s.name, s.slug
ORDER BY sub.name
`

type ListOwnerSublocationsRow struct {
	SublocationID int32         `json:"sublocation_id"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	StateID       int32         `json:"state_id"`
	Slug          string        `json:"slug"`
	Status        string        `json:"status"`
	OwnerID       string        `json:"owner_id"`
	ReviewNote    string        `json:"review_note"`
	Lat           pgtype.Float8 `json:"lat"`
	Lng           pgtype.Float8 `json:"lng"`
	HostName      string        `json:"host_name"`
	HostUrl       string        `json:"host_url"`
	HostSince     pgtype.Date   `json:"host_since"`
	Address       string        `json:"address"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
	StateName     string        `json:"state_name"`
	StateSlug     string        `json:"state_slug"`
	VideoCount    int32         `json:"video_count"`
}

func (q *Queries) ListOwnerSublocations(ctx context.Context, ownerID string) ([]ListOwnerSublocationsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerSublocations, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerSublocationsRow{}
	for rows.Next() {
		var i ListOwnerSublocationsRow
		if err := rows.Scan(
			&i.SublocationID,
			&i.Name,
			&i.Description,
			&i.StateID,
			&i.Slug,
			&i.Status,
			&i.OwnerID,
			&i.ReviewNote,
			&i.Lat,
			&i.Lng,
			&i.HostName,
			&i.HostUrl,
			&i.HostSince,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateSlug,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerVideos = `-- name: ListOwnerVideos :many
SELECT v.video_id, v.title, v.slug, v.src, v.type, v.state_id, v.sublocation_id,
       v.status, v.owner_id, v.stream_id, v.review_note, v.about,
       v.created_at, v.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COALESCE(sub.name, '') AS sublocation_name,
       COALESCE(sub.slug, '') AS sublocation_slug,
       COALESCE(sub.status, '') AS sublocation_status
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.owner_id = $1
ORDER BY v.title
`

type ListOwnerVideosRow struct {
	VideoID           int32       `json:"video_id"`
	Title             string      `json:"title"`
	Slug              string      `json:"slug"`
	Src               string      `json:"src"`
	Type              string      `json:"type"`
	StateID           int32       `json:"state_id"`
	SublocationID     *int32      `json:"sublocation_id"`
	Status            string      `json:"status"`
	OwnerID           string      `json:"owner_id"`
	StreamID          pgtype.Text `json:"stream_id"`
	ReviewNote        string      `json:"review_note"`
	About             string      `json:"about"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	StateName         string      `json:"state_name"`
	StateSlug         string      `json:"state_slug"`
	SublocationName   string      `json:"sublocation_name"`
	SublocationSlug   string      `json:"sublocation_slug"`
	SublocationStatus string      `json:"sublocation_status"`
}

func (q *Queries) ListOwnerVideos(ctx context.Context, ownerID string) ([]ListOwnerVideosRow, error) {
	rows, err := q.db.Query(ctx, listOwnerVideos, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerVideosRow{}
	for rows.Next() {
		var i ListOwnerVideosRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Slug,
			&i.Src,
			&i.Type,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.OwnerID,
			&i.StreamID,
			&i.ReviewNote,
			&i.About,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateSlug,
			&i.SublocationName,
			&i.SublocationSlug,
			&i.SublocationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSublocationStatus = `-- name: SetSublocationStatus :exec
UPDATE sublocations SET status = $2, review_note = $3 WHERE sublocation_id = $1
`

type SetSublocationStatusParams struct {
	SublocationID int32  `json:"sublocation_id"`
	Status        string `json:"status"`
	ReviewNote    string `json:"review_note"`
}

func (q *Queries) SetSublocationStatus(ctx context.Context, arg SetSublocationStatusParams) error {
	_, err := q.db.Exec(ctx, setSublocationStatus, arg.SublocationID, arg.Status, arg.ReviewNote)
	return err
}

const setVideoStatus = `-- name: SetVideoStatus :exec
UPDATE videos SET status = $2, review_note = $3 WHERE video_id = $1
`

type SetVideoStatusParams struct {
	VideoID    int32  `json:"video_id"`
	Status     string `json:"status"`
	ReviewNote string `json:"review_note"`
}

// SetVideoStatus is the one write every status transition goes through
// (pause, resume, approve, reject). The handler decides whether the
// transition is legal — see videoTransition in handler/status.go.
func (q *Queries) SetVideoStatus(ctx context.Context, arg SetVideoStatusParams) error {
	_, err := q.db.Exec(ctx, setVideoStatus, arg.VideoID, arg.Status, arg.ReviewNote)
	return err
}

const updateOwnerSublocation = `-- name: UpdateOwnerSublocation :exec
UPDATE sublocations SET name = $2, description = $3, state_id = $4,
       address = $5, lat = $6, lng = $7, host_name = $8, host_url = $9, host_since = $10
WHERE sublocation_id = $1
`

type UpdateOwnerSublocationParams struct {
	SublocationID int32         `json:"sublocation_id"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	StateID       int32         `json:"state_id"`
	Address       string        `json:"address"`
	Lat           pgtype.Float8 `json:"lat"`
	Lng           pgtype.Float8 `json:"lng"`
	HostName      string        `json:"host_name"`
	HostUrl       string        `json:"host_url"`
	HostSince     pgtype.Date   `json:"host_since"`
}

// UpdateOwnerSublocation leaves status alone: an owner edit never re-enters
// or leaves review by itself.
func (q *Queries) UpdateOwnerSublocation(ctx context.Context, arg UpdateOwnerSublocationParams) error {
	_, err := q.db.Exec(ctx, updateOwnerSublocation,
		arg.SublocationID,
		arg.Name,
		arg.Description,
		arg.StateID,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.HostName,
		arg.HostUrl,
		arg.HostSince,
	)
	return err
}

const updateOwnerVideo = `-- name: UpdateOwnerVideo :exec
UPDATE videos SET title = $2, about = $3 WHERE video_id = $1
`

type UpdateOwnerVideoParams struct {
	VideoID int32  `json:"video_id"`
	Title   string `json:"title"`
	About   string `json:"about"`
}

func (q *Queries) UpdateOwnerVideo(ctx context.Context, arg UpdateOwnerVideoParams) error {
	_, err := q.db.Exec(ctx, updateOwnerVideo, arg.VideoID, arg.Title, arg.About)
	return err
}
