// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Ad struct {
	AdID          int32              `json:"ad_id"`
	Name          string             `json:"name"`
	VideoUrl      string             `json:"video_url"`
	ClickUrl      string             `json:"click_url"`
	Weight        int32              `json:"weight"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	Enabled       bool               `json:"enabled"`
	StateID       *int32             `json:"state_id"`
	SublocationID *int32             `json:"sublocation_id"`
	VideoID       *int32             `json:"video_id"`
	CreatedBy     string             `json:"created_by"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	Type          string             `json:"type"`
	HtmlCode      string             `json:"html_code"`
	Placement     string             `json:"placement"`
	IsOverride    bool               `json:"is_override"`
}

type AdImpression struct {
	ImpressionID int64     `json:"impression_id"`
	AdID         int32     `json:"ad_id"`
	VideoID      *int32    `json:"video_id"`
	Kind         string    `json:"kind"`
	CreatedAt    time.Time `json:"created_at"`
}

type State struct {
	StateID     int32     `json:"state_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Slug        string    `json:"slug"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Sublocation struct {
	SublocationID int32     `json:"sublocation_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	StateID       int32     `json:"state_id"`
	Slug          string    `json:"slug"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Video struct {
	VideoID       int32     `json:"video_id"`
	Title         string    `json:"title"`
	Src           string    `json:"src"`
	Type          string    `json:"type"`
	StateID       int32     `json:"state_id"`
	SublocationID *int32    `json:"sublocation_id"`
	Status        string    `json:"status"`
	CreatedBy     string    `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Slug          string    `json:"slug"`
	ViewCount     int64     `json:"view_count"`
}
