// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: posts.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, body_md, excerpt, cover_url, state_id, sublocation_id,
                    video_id, status, published_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING post_id, title, slug, body_md, excerpt, cover_url, state_id, sublocation_id, video_id, status, published_at, created_by, created_at, updated_at
`

type CreatePostParams struct {
	Title         string             `json:"title"`
	BodyMd        string             `json:"body_md"`
	Excerpt       string             `json:"excerpt"`
	CoverUrl      string             `json:"cover_url"`
	StateID       *int32             `json:"state_id"`
	SublocationID *int32             `json:"sublocation_id"`
	VideoID       *int32             `json:"video_id"`
	Status        string             `json:"status"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedBy     string             `json:"created_by"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.BodyMd,
		arg.Excerpt,
		arg.CoverUrl,
		arg.StateID,
		arg.SublocationID,
		arg.VideoID,
		arg.Status,
		arg.PublishedAt,
		arg.CreatedBy,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Slug,
		&i.BodyMd,
		&i.Excerpt,
		&i.CoverUrl,
		&i.StateID,
		&i.SublocationID,
		&i.VideoID,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE post_id = $1
`

func (q *Queries) DeletePost(ctx context.Context, postID int32) error {
	_, err := q.db.Exec(ctx, deletePost, postID)
	return err
}

const getPost = `-- name: GetPost :one

SELECT post_id, title, slug, body_md, excerpt, cover_url, state_id, sublocation_id, video_id, status, published_at, created_by, created_at, updated_at FROM posts WHERE post_id = $1
`

// Field notes (posts) queries.
//
// Scope is whichever of state_id/sublocation_id/video_id is set on the row
// (same pattern as ads); all three NULL is an unscoped post shown only at
// /notes. Every public-facing query filters status = 'published' so a draft
// is never reachable outside the admin listing.
func (q *Queries) GetPost(ctx context.Context, postID int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, postID)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Slug,
		&i.BodyMd,
		&i.Excerpt,
		&i.CoverUrl,
		&i.StateID,
		&i.SublocationID,
		&i.VideoID,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPostBySlug = `-- name: GetPublishedPostBySlug :one
SELECT p.post_id, p.title, p.slug, p.body_md, p.excerpt, p.cover_url,
       p.state_id, p.sublocation_id, p.video_id, p.status, p.published_at,
       p.created_by, p.created_at, p.updated_at,
       COALESCE(st.name, substate.name, vstate.name, '') AS state_name,
       COALESCE(st.slug, substate.slug, vstate.slug, '') AS state_slug,
       COALESCE(sub.name, vsub.name, '') AS sublocation_name,
       COALESCE(sub.slug, vsub.slug, '') AS sublocation_slug,
       COALESCE(v.title, '') AS video_title,
       COALESCE(v.slug, '') AS video_slug
FROM posts p
LEFT JOIN states st ON st.state_id = p.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = p.sublocation_id
LEFT JOIN states substate ON substate.state_id = sub.state_id
LEFT JOIN videos v ON v.video_id = p.video_id
LEFT JOIN sublocations vsub ON vsub.sublocation_id = v.sublocation_id
LEFT JOIN states vstate ON vstate.state_id = v.state_id
WHERE p.slug = $1 AND p.status = 'published'
`

type GetPublishedPostBySlugRow struct {
	PostID          int32              `json:"post_id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	BodyMd          string             `json:"body_md"`
	Excerpt         string             `json:"excerpt"`
	CoverUrl        string             `json:"cover_url"`
	StateID         *int32             `json:"state_id"`
	SublocationID   *int32             `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	StateName       string             `json:"state_name"`
	StateSlug       string             `json:"state_slug"`
	SublocationName string             `json:"sublocation_name"`
	SublocationSlug string             `json:"sublocation_slug"`
	VideoTitle      string             `json:"video_title"`
	VideoSlug       string             `json:"video_slug"`
}

// GetPublishedPostBySlug backs GET /posts/{slug} — same scope-name shape as
// ListPublishedPosts, published only (else the handler returns 404).
func (q *Queries) GetPublishedPostBySlug(ctx context.Context, slug string) (GetPublishedPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedPostBySlug, slug)
	var i GetPublishedPostBySlugRow
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Slug,
		&i.BodyMd,
		&i.Excerpt,
		&i.CoverUrl,
		&i.StateID,
		&i.SublocationID,
		&i.VideoID,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.StateSlug,
		&i.SublocationName,
		&i.SublocationSlug,
		&i.VideoTitle,
		&i.VideoSlug,
	)
	return i, err
}

const listAllPosts = `-- name: ListAllPosts :many
SELECT p.post_id, p.title, p.slug, p.body_md, p.excerpt, p.cover_url,
       p.state_id, p.sublocation_id, p.video_id, p.status, p.published_at,
       p.created_by, p.created_at, p.updated_at,
       COALESCE(st.name, '') AS state_name,
       COALESCE(sub.name, '') AS sublocation_name,
       COALESCE(v.title, '') AS video_title
FROM posts p
LEFT JOIN states st ON st.state_id = p.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = p.sublocation_id
LEFT JOIN videos v ON v.video_id = p.video_id
ORDER BY p.created_at DESC
`

type ListAllPostsRow struct {
	PostID          int32              `json:"post_id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	BodyMd          string             `json:"body_md"`
	Excerpt         string             `json:"excerpt"`
	CoverUrl        string             `json:"cover_url"`
	StateID         *int32             `json:"state_id"`
	SublocationID   *int32             `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	StateName       string             `json:"state_name"`
	SublocationName string             `json:"sublocation_name"`
	VideoTitle      string             `json:"video_title"`
}

// ListAllPosts backs the admin dashboard — every post regardless of status,
// newest first, with the scope names the list row displays.
func (q *Queries) ListAllPosts(ctx context.Context) ([]ListAllPostsRow, error) {
	rows, err := q.db.Query(ctx, listAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPostsRow{}
	for rows.Next() {
		var i ListAllPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Slug,
			&i.BodyMd,
			&i.Excerpt,
			&i.CoverUrl,
			&i.StateID,
			&i.SublocationID,
			&i.VideoID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
			&i.VideoTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT p.post_id, p.title, p.slug, p.body_md, p.excerpt, p.cover_url,
       p.state_id, p.sublocation_id, p.video_id, p.status, p.published_at,
       p.created_by, p.created_at, p.updated_at,
       COALESCE(st.name, substate.name, vstate.name, '') AS state_name,
       COALESCE(st.slug, substate.slug, vstate.slug, '') AS state_slug,
       COALESCE(sub.name, vsub.name, '') AS sublocation_name,
       COALESCE(sub.slug, vsub.slug, '') AS sublocation_slug,
       COALESCE(v.title, '') AS video_title,
       COALESCE(v.slug, '') AS video_slug
FROM posts p
LEFT JOIN states st ON st.state_id = p.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = p.sublocation_id
LEFT JOIN states substate ON substate.state_id = sub.state_id
LEFT JOIN videos v ON v.video_id = p.video_id
LEFT JOIN sublocations vsub ON vsub.sublocation_id = v.sublocation_id
LEFT JOIN states vstate ON vstate.state_id = v.state_id
WHERE p.status = 'published'
ORDER BY p.published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedPostsRow struct {
	PostID          int32              `json:"post_id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	BodyMd          string             `json:"body_md"`
	Excerpt         string             `json:"excerpt"`
	CoverUrl        string             `json:"cover_url"`
	StateID         *int32             `json:"state_id"`
	SublocationID   *int32             `json:"sublocation_id"`
	VideoID         *int32             `json:"video_id"`
	Status          string             `json:"status"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	StateName       string             `json:"state_name"`
	StateSlug       string             `json:"state_slug"`
	SublocationName string             `json:"sublocation_name"`
	SublocationSlug string             `json:"sublocation_slug"`
	VideoTitle      string             `json:"video_title"`
	VideoSlug       string             `json:"video_slug"`
}

// ListPublishedPosts backs GET /posts (no scope filter) — newest published
// first, paginated. The handler requests limit+1 rows to detect a next page
// without a separate count query. state_name/state_slug and
// sublocation_name/sublocation_slug are resolved from whichever attachment is
// actually set, so the list and article pages can link straight to the
// camera/sublocation/state without a second round trip:
//
//	state scope       -> st   (the post's own state_id)
//	sublocation scope  -> sub for the sublocation itself, substate for its
//	                      parent state (a post has no direct state_id here)
//	camera scope       -> v for the title/slug, vsub/vstate for the camera's
//	                      own sublocation/state (a post has neither directly)
func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPostsRow{}
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Slug,
			&i.BodyMd,
			&i.Excerpt,
			&i.CoverUrl,
			&i.StateID,
			&i.SublocationID,
			&i.VideoID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateSlug,
			&i.SublocationName,
			&i.SublocationSlug,
			&i.VideoTitle,
			&i.VideoSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByState = `-- name: ListPublishedPostsByState :many

SELECT post_id, title, slug, body_md, excerpt, cover_url, state_id, sublocation_id, video_id, status, published_at, created_by, created_at, updated_at FROM posts
WHERE status = 'published' AND state_id = $1
ORDER BY published_at DESC
LIMIT $2
`

type ListPublishedPostsByStateParams struct {
	StateID *int32 `json:"state_id"`
	Limit   int32  `json:"limit"`
}

// The three ByX queries back the related-notes block on a state/sublocation/
// camera page (limit 3) — plain Post rows are enough there since the caller
// already knows the scope it asked for.
func (q *Queries) ListPublishedPostsByState(ctx context.Context, arg ListPublishedPostsByStateParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByState, arg.StateID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Slug,
			&i.BodyMd,
			&i.Excerpt,
			&i.CoverUrl,
			&i.StateID,
			&i.SublocationID,
			&i.VideoID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsBySublocation = `-- name: ListPublishedPostsBySublocation :many
SELECT post_id, title, slug, body_md, excerpt, cover_url, state_id, sublocation_id, video_id, status, published_at, created_by, created_at, updated_at FROM posts
WHERE status = 'published' AND sublocation_id = $1
ORDER BY published_at DESC
LIMIT $2
`

type ListPublishedPostsBySublocationParams struct {
	SublocationID *int32 `json:"sublocation_id"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) ListPublishedPostsBySublocation(ctx context.Context, arg ListPublishedPostsBySublocationParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsBySublocation, arg.SublocationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Slug,
			&i.BodyMd,
			&i.Excerpt,
			&i.CoverUrl,
			&i.StateID,
			&i.SublocationID,
			&i.VideoID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPostsByVideo = `-- name: ListPublishedPostsByVideo :many
SELECT post_id, title, slug, body_md, excerpt, cover_url, state_id, sublocation_id, video_id, status, published_at, created_by, created_at, updated_at FROM posts
WHERE status = 'published' AND video_id = $1
ORDER BY published_at DESC
LIMIT $2
`

type ListPublishedPostsByVideoParams struct {
	VideoID *int32 `json:"video_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListPublishedPostsByVideo(ctx context.Context, arg ListPublishedPostsByVideoParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPostsByVideo, arg.VideoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Slug,
			&i.BodyMd,
			&i.Excerpt,
			&i.CoverUrl,
			&i.StateID,
			&i.SublocationID,
			&i.VideoID,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET title = $2, body_md = $3, excerpt = $4, cover_url = $5,
                 state_id = $6, sublocation_id = $7, video_id = $8,
                 status = $9, published_at = $10
WHERE post_id = $1
RETURNING post_id, title, slug, body_md, excerpt, cover_url, state_id, sublocation_id, video_id, status, published_at, created_by, created_at, updated_at
`

type UpdatePostParams struct {
	PostID        int32              `json:"post_id"`
	Title         string             `json:"title"`
	BodyMd        string             `json:"body_md"`
	Excerpt       string             `json:"excerpt"`
	CoverUrl      string             `json:"cover_url"`
	StateID       *int32             `json:"state_id"`
	SublocationID *int32             `json:"sublocation_id"`
	VideoID       *int32             `json:"video_id"`
	Status        string             `json:"status"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.PostID,
		arg.Title,
		arg.BodyMd,
		arg.Excerpt,
		arg.CoverUrl,
		arg.StateID,
		arg.SublocationID,
		arg.VideoID,
		arg.Status,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.Title,
		&i.Slug,
		&i.BodyMd,
		&i.Excerpt,
		&i.CoverUrl,
		&i.StateID,
		&i.SublocationID,
		&i.VideoID,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
