// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: review.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPendingSublocations = `-- name: ListPendingSublocations :many

SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.status, sub.owner_id, sub.review_note,
       sub.lat, sub.lng, sub.host_name, sub.host_url, sub.host_since, sub.address,
       sub.created_at, sub.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id
WHERE sub.status = 'pending'
GROUP BY sub.sublocation_id, s.name, s.slug
ORDER BY sub.created_at
`

type ListPendingSublocationsRow struct {
	SublocationID int32         `json:"sublocation_id"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	StateID       int32         `json:"state_id"`
	Slug          string        `json:"slug"`
	Status        string        `json:"status"`
	OwnerID       string        `json:"owner_id"`
	ReviewNote    string        `json:"review_note"`
	Lat           pgtype.Float8 `json:"lat"`
	Lng           pgtype.Float8 `json:"lng"`
	HostName      string        `json:"host_name"`
	HostUrl       string        `json:"host_url"`
	HostSince     pgtype.Date   `json:"host_since"`
	Address       string        `json:"address"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
	StateName     string        `json:"state_name"`
	StateSlug     string        `json:"state_slug"`
	VideoCount    int32         `json:"video_count"`
}

// Admin review queue (DAN-39): GET /review and the approve/reject cascades.
func (q *Queries) ListPendingSublocations(ctx context.Context) ([]ListPendingSublocationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSublocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSublocationsRow{}
	for rows.Next() {
		var i ListPendingSublocationsRow
		if err := rows.Scan(
			&i.SublocationID,
			&i.Name,
			&i.Description,
			&i.StateID,
			&i.Slug,
			&i.Status,
			&i.OwnerID,
			&i.ReviewNote,
			&i.Lat,
			&i.Lng,
			&i.HostName,
			&i.HostUrl,
			&i.HostSince,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateSlug,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingVideos = `-- name: ListPendingVideos :many
SELECT v.video_id, v.title, v.slug, v.src, v.type, v.state_id, v.sublocation_id,
       v.status, v.owner_id, v.stream_id, v.review_note, v.about,
       v.created_at, v.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COALESCE(sub.name, '') AS sublocation_name,
       COALESCE(sub.slug, '') AS sublocation_slug,
       COALESCE(sub.status, '') AS sublocation_status
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.status = 'pending'
ORDER BY v.created_at
`

type ListPendingVideosRow struct {
	VideoID           int32       `json:"video_id"`
	Title             string      `json:"title"`
	Slug              string      `json:"slug"`
	Src               string      `json:"src"`
	Type              string      `json:"type"`
	StateID           int32       `json:"state_id"`
	SublocationID     *int32      `json:"sublocation_id"`
	Status            string      `json:"status"`
	OwnerID           string      `json:"owner_id"`
	StreamID          pgtype.Text `json:"stream_id"`
	ReviewNote        string      `json:"review_note"`
	About             string      `json:"about"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	StateName         string      `json:"state_name"`
	StateSlug         string      `json:"state_slug"`
	SublocationName   string      `json:"sublocation_name"`
	SublocationSlug   string      `json:"sublocation_slug"`
	SublocationStatus string      `json:"sublocation_status"`
}

func (q *Queries) ListPendingVideos(ctx context.Context) ([]ListPendingVideosRow, error) {
	rows, err := q.db.Query(ctx, listPendingVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingVideosRow{}
	for rows.Next() {
		var i ListPendingVideosRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Slug,
			&i.Src,
			&i.Type,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.OwnerID,
			&i.StreamID,
			&i.ReviewNote,
			&i.About,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateSlug,
			&i.SublocationName,
			&i.SublocationSlug,
			&i.SublocationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPendingVideosInSublocation = `-- name: RejectPendingVideosInSublocation :many
UPDATE videos SET status = 'rejected', review_note = $2
WHERE sublocation_id = $1 AND status = 'pending'
RETURNING video_id, stream_id
`

type RejectPendingVideosInSublocationParams struct {
	SublocationID *int32 `json:"sublocation_id"`
	ReviewNote    string `json:"review_note"`
}

type RejectPendingVideosInSublocationRow struct {
	VideoID  int32       `json:"video_id"`
	StreamID pgtype.Text `json:"stream_id"`
}

// RejectPendingVideosInSublocation is the cascade when a sublocation is
// rejected: its still-pending cameras are rejected with the same note. The
// stream ids come back so the handler can stop each Restreamer process.
func (q *Queries) RejectPendingVideosInSublocation(ctx context.Context, arg RejectPendingVideosInSublocationParams) ([]RejectPendingVideosInSublocationRow, error) {
	rows, err := q.db.Query(ctx, rejectPendingVideosInSublocation, arg.SublocationID, arg.ReviewNote)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RejectPendingVideosInSublocationRow{}
	for rows.Next() {
		var i RejectPendingVideosInSublocationRow
		if err := rows.Scan(&i.VideoID, &i.StreamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
