// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: sublocations.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSublocation = `-- name: CreateSublocation :one
INSERT INTO sublocations (name, description, state_id, hero_url, hero_kind, logo_url, sponsor_url, sponsor_link, about,
                          lat, lng, host_name, host_url, host_since, address, title_url, tourism_name, tourism_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING sublocation_id, name, description, state_id, slug,
          hero_url, hero_kind, logo_url, sponsor_url, sponsor_link, title_url, tourism_name, tourism_url, about,
          lat, lng, host_name, host_url, host_since, address,
          created_at, updated_at
`

type CreateSublocationParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	StateID     int32         `json:"state_id"`
	HeroUrl     string        `json:"hero_url"`
	HeroKind    string        `json:"hero_kind"`
	LogoUrl     string        `json:"logo_url"`
	SponsorUrl  string        `json:"sponsor_url"`
	SponsorLink string        `json:"sponsor_link"`
	About       string        `json:"about"`
	Lat         pgtype.Float8 `json:"lat"`
	Lng         pgtype.Float8 `json:"lng"`
	HostName    string        `json:"host_name"`
	HostUrl     string        `json:"host_url"`
	HostSince   pgtype.Date   `json:"host_since"`
	Address     string        `json:"address"`
	TitleUrl    string        `json:"title_url"`
	TourismName string        `json:"tourism_name"`
	TourismUrl  string        `json:"tourism_url"`
}

type CreateSublocationRow struct {
	SublocationID int32         `json:"sublocation_id"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	StateID       int32         `json:"state_id"`
	Slug          string        `json:"slug"`
	HeroUrl       string        `json:"hero_url"`
	HeroKind      string        `json:"hero_kind"`
	LogoUrl       string        `json:"logo_url"`
	SponsorUrl    string        `json:"sponsor_url"`
	SponsorLink   string        `json:"sponsor_link"`
	TitleUrl      string        `json:"title_url"`
	TourismName   string        `json:"tourism_name"`
	TourismUrl    string        `json:"tourism_url"`
	About         string        `json:"about"`
	Lat           pgtype.Float8 `json:"lat"`
	Lng           pgtype.Float8 `json:"lng"`
	HostName      string        `json:"host_name"`
	HostUrl       string        `json:"host_url"`
	HostSince     pgtype.Date   `json:"host_since"`
	Address       string        `json:"address"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

func (q *Queries) CreateSublocation(ctx context.Context, arg CreateSublocationParams) (CreateSublocationRow, error) {
	row := q.db.QueryRow(ctx, createSublocation,
		arg.Name,
		arg.Description,
		arg.StateID,
		arg.HeroUrl,
		arg.HeroKind,
		arg.LogoUrl,
		arg.SponsorUrl,
		arg.SponsorLink,
		arg.About,
		arg.Lat,
		arg.Lng,
		arg.HostName,
		arg.HostUrl,
		arg.HostSince,
		arg.Address,
		arg.TitleUrl,
		arg.TourismName,
		arg.TourismUrl,
	)
	var i CreateSublocationRow
	err := row.Scan(
		&i.SublocationID,
		&i.Name,
		&i.Description,
		&i.StateID,
		&i.Slug,
		&i.HeroUrl,
		&i.HeroKind,
		&i.LogoUrl,
		&i.SponsorUrl,
		&i.SponsorLink,
		&i.TitleUrl,
		&i.TourismName,
		&i.TourismUrl,
		&i.About,
		&i.Lat,
		&i.Lng,
		&i.HostName,
		&i.HostUrl,
		&i.HostSince,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSublocation = `-- name: DeleteSublocation :exec
DELETE FROM sublocations WHERE sublocation_id = $1
`

func (q *Queries) DeleteSublocation(ctx context.Context, sublocationID int32) error {
	_, err := q.db.Exec(ctx, deleteSublocation, sublocationID)
	return err
}

const getSublocationByID = `-- name: GetSublocationByID :one
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.hero_url, sub.hero_kind, sub.logo_url, sub.sponsor_url, sub.sponsor_link, sub.title_url, sub.tourism_name, sub.tourism_url, sub.about,
       sub.lat, sub.lng, sub.host_name, sub.host_url, sub.host_since, sub.address,
       sub.created_at, sub.updated_at,
       s.name AS state_name,
       s.tourism_name AS state_tourism_name, s.tourism_url AS state_tourism_url,
       COALESCE((SELECT v2.src FROM videos v2
                 WHERE v2.sublocation_id = sub.sublocation_id AND v2.status = 'active'
                 ORDER BY v2.video_id LIMIT 1), '')::text AS first_src,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id AND v.status = 'active'
WHERE sub.sublocation_id = $1
GROUP BY sub.sublocation_id, s.name, s.tourism_name, s.tourism_url
`

type GetSublocationByIDRow struct {
	SublocationID    int32         `json:"sublocation_id"`
	Name             string        `json:"name"`
	Description      string        `json:"description"`
	StateID          int32         `json:"state_id"`
	Slug             string        `json:"slug"`
	HeroUrl          string        `json:"hero_url"`
	HeroKind         string        `json:"hero_kind"`
	LogoUrl          string        `json:"logo_url"`
	SponsorUrl       string        `json:"sponsor_url"`
	SponsorLink      string        `json:"sponsor_link"`
	TitleUrl         string        `json:"title_url"`
	TourismName      string        `json:"tourism_name"`
	TourismUrl       string        `json:"tourism_url"`
	About            string        `json:"about"`
	Lat              pgtype.Float8 `json:"lat"`
	Lng              pgtype.Float8 `json:"lng"`
	HostName         string        `json:"host_name"`
	HostUrl          string        `json:"host_url"`
	HostSince        pgtype.Date   `json:"host_since"`
	Address          string        `json:"address"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	StateName        string        `json:"state_name"`
	StateTourismName string        `json:"state_tourism_name"`
	StateTourismUrl  string        `json:"state_tourism_url"`
	FirstSrc         string        `json:"first_src"`
	VideoCount       int32         `json:"video_count"`
}

func (q *Queries) GetSublocationByID(ctx context.Context, sublocationID int32) (GetSublocationByIDRow, error) {
	row := q.db.QueryRow(ctx, getSublocationByID, sublocationID)
	var i GetSublocationByIDRow
	err := row.Scan(
		&i.SublocationID,
		&i.Name,
		&i.Description,
		&i.StateID,
		&i.Slug,
		&i.HeroUrl,
		&i.HeroKind,
		&i.LogoUrl,
		&i.SponsorUrl,
		&i.SponsorLink,
		&i.TitleUrl,
		&i.TourismName,
		&i.TourismUrl,
		&i.About,
		&i.Lat,
		&i.Lng,
		&i.HostName,
		&i.HostUrl,
		&i.HostSince,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.StateTourismName,
		&i.StateTourismUrl,
		&i.FirstSrc,
		&i.VideoCount,
	)
	return i, err
}

const getSublocationBySlug = `-- name: GetSublocationBySlug :one
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.hero_url, sub.hero_kind, sub.logo_url, sub.sponsor_url, sub.sponsor_link, sub.title_url, sub.tourism_name, sub.tourism_url, sub.about,
       sub.lat, sub.lng, sub.host_name, sub.host_url, sub.host_since, sub.address,
       sub.created_at, sub.updated_at,
       s.name AS state_name,
       s.tourism_name AS state_tourism_name, s.tourism_url AS state_tourism_url,
       COALESCE((SELECT v2.src FROM videos v2
                 WHERE v2.sublocation_id = sub.sublocation_id AND v2.status = 'active'
                 ORDER BY v2.video_id LIMIT 1), '')::text AS first_src,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id AND v.status = 'active'
WHERE sub.slug = $1
GROUP BY sub.sublocation_id, s.name, s.tourism_name, s.tourism_url
`

type GetSublocationBySlugRow struct {
	SublocationID    int32         `json:"sublocation_id"`
	Name             string        `json:"name"`
	Description      string        `json:"description"`
	StateID          int32         `json:"state_id"`
	Slug             string        `json:"slug"`
	HeroUrl          string        `json:"hero_url"`
	HeroKind         string        `json:"hero_kind"`
	LogoUrl          string        `json:"logo_url"`
	SponsorUrl       string        `json:"sponsor_url"`
	SponsorLink      string        `json:"sponsor_link"`
	TitleUrl         string        `json:"title_url"`
	TourismName      string        `json:"tourism_name"`
	TourismUrl       string        `json:"tourism_url"`
	About            string        `json:"about"`
	Lat              pgtype.Float8 `json:"lat"`
	Lng              pgtype.Float8 `json:"lng"`
	HostName         string        `json:"host_name"`
	HostUrl          string        `json:"host_url"`
	HostSince        pgtype.Date   `json:"host_since"`
	Address          string        `json:"address"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	StateName        string        `json:"state_name"`
	StateTourismName string        `json:"state_tourism_name"`
	StateTourismUrl  string        `json:"state_tourism_url"`
	FirstSrc         string        `json:"first_src"`
	VideoCount       int32         `json:"video_count"`
}

func (q *Queries) GetSublocationBySlug(ctx context.Context, slug string) (GetSublocationBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSublocationBySlug, slug)
	var i GetSublocationBySlugRow
	err := row.Scan(
		&i.SublocationID,
		&i.Name,
		&i.Description,
		&i.StateID,
		&i.Slug,
		&i.HeroUrl,
		&i.HeroKind,
		&i.LogoUrl,
		&i.SponsorUrl,
		&i.SponsorLink,
		&i.TitleUrl,
		&i.TourismName,
		&i.TourismUrl,
		&i.About,
		&i.Lat,
		&i.Lng,
		&i.HostName,
		&i.HostUrl,
		&i.HostSince,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.StateTourismName,
		&i.StateTourismUrl,
		&i.FirstSrc,
		&i.VideoCount,
	)
	return i, err
}

const listSublocationsByState = `-- name: ListSublocationsByState :many
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.hero_url, sub.hero_kind, sub.logo_url, sub.sponsor_url, sub.sponsor_link, sub.title_url, sub.tourism_name, sub.tourism_url, sub.about,
       sub.lat, sub.lng, sub.host_name, sub.host_url, sub.host_since, sub.address,
       sub.created_at, sub.updated_at,
       s.name AS state_name,
       s.tourism_name AS state_tourism_name, s.tourism_url AS state_tourism_url,
       COALESCE((SELECT v2.src FROM videos v2
                 WHERE v2.sublocation_id = sub.sublocation_id AND v2.status = 'active'
                 ORDER BY v2.video_id LIMIT 1), '')::text AS first_src,
       COUNT(v.video_id)::int AS video_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id AND v.status = 'active'
WHERE sub.state_id = $1
GROUP BY sub.sublocation_id, s.name, s.tourism_name, s.tourism_url
ORDER BY sub.name
`

type ListSublocationsByStateRow struct {
	SublocationID    int32         `json:"sublocation_id"`
	Name             string        `json:"name"`
	Description      string        `json:"description"`
	StateID          int32         `json:"state_id"`
	Slug             string        `json:"slug"`
	HeroUrl          string        `json:"hero_url"`
	HeroKind         string        `json:"hero_kind"`
	LogoUrl          string        `json:"logo_url"`
	SponsorUrl       string        `json:"sponsor_url"`
	SponsorLink      string        `json:"sponsor_link"`
	TitleUrl         string        `json:"title_url"`
	TourismName      string        `json:"tourism_name"`
	TourismUrl       string        `json:"tourism_url"`
	About            string        `json:"about"`
	Lat              pgtype.Float8 `json:"lat"`
	Lng              pgtype.Float8 `json:"lng"`
	HostName         string        `json:"host_name"`
	HostUrl          string        `json:"host_url"`
	HostSince        pgtype.Date   `json:"host_since"`
	Address          string        `json:"address"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	StateName        string        `json:"state_name"`
	StateTourismName string        `json:"state_tourism_name"`
	StateTourismUrl  string        `json:"state_tourism_url"`
	FirstSrc         string        `json:"first_src"`
	VideoCount       int32         `json:"video_count"`
}

func (q *Queries) ListSublocationsByState(ctx context.Context, stateID int32) ([]ListSublocationsByStateRow, error) {
	rows, err := q.db.Query(ctx, listSublocationsByState, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSublocationsByStateRow{}
	for rows.Next() {
		var i ListSublocationsByStateRow
		if err := rows.Scan(
			&i.SublocationID,
			&i.Name,
			&i.Description,
			&i.StateID,
			&i.Slug,
			&i.HeroUrl,
			&i.HeroKind,
			&i.LogoUrl,
			&i.SponsorUrl,
			&i.SponsorLink,
			&i.TitleUrl,
			&i.TourismName,
			&i.TourismUrl,
			&i.About,
			&i.Lat,
			&i.Lng,
			&i.HostName,
			&i.HostUrl,
			&i.HostSince,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateTourismName,
			&i.StateTourismUrl,
			&i.FirstSrc,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSublocationsPaginated = `-- name: ListSublocationsPaginated :many
SELECT sub.sublocation_id, sub.name, sub.description, sub.state_id, sub.slug,
       sub.hero_url, sub.hero_kind, sub.logo_url, sub.sponsor_url, sub.sponsor_link, sub.title_url, sub.tourism_name, sub.tourism_url, sub.about,
       sub.lat, sub.lng, sub.host_name, sub.host_url, sub.host_since, sub.address,
       sub.created_at, sub.updated_at,
       s.name AS state_name,
       s.tourism_name AS state_tourism_name, s.tourism_url AS state_tourism_url,
       COALESCE((SELECT v2.src FROM videos v2
                 WHERE v2.sublocation_id = sub.sublocation_id AND v2.status = 'active'
                 ORDER BY v2.video_id LIMIT 1), '')::text AS first_src,
       COUNT(v.video_id)::int AS video_count,
       COUNT(*) OVER()::int AS total_count
FROM sublocations sub
JOIN states s ON s.state_id = sub.state_id
LEFT JOIN videos v ON v.sublocation_id = sub.sublocation_id AND v.status = 'active'
GROUP BY sub.sublocation_id, s.name, s.tourism_name, s.tourism_url
ORDER BY sub.name
LIMIT $1 OFFSET $2
`

type ListSublocationsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSublocationsPaginatedRow struct {
	SublocationID    int32         `json:"sublocation_id"`
	Name             string        `json:"name"`
	Description      string        `json:"description"`
	StateID          int32         `json:"state_id"`
	Slug             string        `json:"slug"`
	HeroUrl          string        `json:"hero_url"`
	HeroKind         string        `json:"hero_kind"`
	LogoUrl          string        `json:"logo_url"`
	SponsorUrl       string        `json:"sponsor_url"`
	SponsorLink      string        `json:"sponsor_link"`
	TitleUrl         string        `json:"title_url"`
	TourismName      string        `json:"tourism_name"`
	TourismUrl       string        `json:"tourism_url"`
	About            string        `json:"about"`
	Lat              pgtype.Float8 `json:"lat"`
	Lng              pgtype.Float8 `json:"lng"`
	HostName         string        `json:"host_name"`
	HostUrl          string        `json:"host_url"`
	HostSince        pgtype.Date   `json:"host_since"`
	Address          string        `json:"address"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	StateName        string        `json:"state_name"`
	StateTourismName string        `json:"state_tourism_name"`
	StateTourismUrl  string        `json:"state_tourism_url"`
	FirstSrc         string        `json:"first_src"`
	VideoCount       int32         `json:"video_count"`
	TotalCount       int32         `json:"total_count"`
}

func (q *Queries) ListSublocationsPaginated(ctx context.Context, arg ListSublocationsPaginatedParams) ([]ListSublocationsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listSublocationsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSublocationsPaginatedRow{}
	for rows.Next() {
		var i ListSublocationsPaginatedRow
		if err := rows.Scan(
			&i.SublocationID,
			&i.Name,
			&i.Description,
			&i.StateID,
			&i.Slug,
			&i.HeroUrl,
			&i.HeroKind,
			&i.LogoUrl,
			&i.SponsorUrl,
			&i.SponsorLink,
			&i.TitleUrl,
			&i.TourismName,
			&i.TourismUrl,
			&i.About,
			&i.Lat,
			&i.Lng,
			&i.HostName,
			&i.HostUrl,
			&i.HostSince,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateTourismName,
			&i.StateTourismUrl,
			&i.FirstSrc,
			&i.VideoCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSublocation = `-- name: UpdateSublocation :exec
UPDATE sublocations SET name = $2, description = $3, state_id = $4,
       hero_url = $5, hero_kind = $6, logo_url = $7, sponsor_url = $8, sponsor_link = $9,
       about = $10,
       lat = $11, lng = $12, host_name = $13, host_url = $14, host_since = $15, address = $16,
       title_url = $17, tourism_name = $18, tourism_url = $19
WHERE sublocation_id = $1
`

type UpdateSublocationParams struct {
	SublocationID int32         `json:"sublocation_id"`
	Name          string        `json:"name"`
	Description   string        `json:"description"`
	StateID       int32         `json:"state_id"`
	HeroUrl       string        `json:"hero_url"`
	HeroKind      string        `json:"hero_kind"`
	LogoUrl       string        `json:"logo_url"`
	SponsorUrl    string        `json:"sponsor_url"`
	SponsorLink   string        `json:"sponsor_link"`
	About         string        `json:"about"`
	Lat           pgtype.Float8 `json:"lat"`
	Lng           pgtype.Float8 `json:"lng"`
	HostName      string        `json:"host_name"`
	HostUrl       string        `json:"host_url"`
	HostSince     pgtype.Date   `json:"host_since"`
	Address       string        `json:"address"`
	TitleUrl      string        `json:"title_url"`
	TourismName   string        `json:"tourism_name"`
	TourismUrl    string        `json:"tourism_url"`
}

func (q *Queries) UpdateSublocation(ctx context.Context, arg UpdateSublocationParams) error {
	_, err := q.db.Exec(ctx, updateSublocation,
		arg.SublocationID,
		arg.Name,
		arg.Description,
		arg.StateID,
		arg.HeroUrl,
		arg.HeroKind,
		arg.LogoUrl,
		arg.SponsorUrl,
		arg.SponsorLink,
		arg.About,
		arg.Lat,
		arg.Lng,
		arg.HostName,
		arg.HostUrl,
		arg.HostSince,
		arg.Address,
		arg.TitleUrl,
		arg.TourismName,
		arg.TourismUrl,
	)
	return err
}
