// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package db

import (
	"context"
)

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (name, email, message, kind)
VALUES ($1, $2, $3, $4)
`

type CreateSubmissionParams struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Message string `json:"message"`
	Kind    string `json:"kind"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.Exec(ctx, createSubmission,
		arg.Name,
		arg.Email,
		arg.Message,
		arg.Kind,
	)
	return err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT submission_id, name, email, message, kind, handled, created_at
FROM submissions
ORDER BY created_at DESC
LIMIT 200
`

func (q *Queries) ListSubmissions(ctx context.Context) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.SubmissionID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.Kind,
			&i.Handled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubmissionHandled = `-- name: SetSubmissionHandled :one
UPDATE submissions SET handled = $2
WHERE submission_id = $1
RETURNING submission_id, name, email, message, kind, handled, created_at
`

type SetSubmissionHandledParams struct {
	SubmissionID int64 `json:"submission_id"`
	Handled      bool  `json:"handled"`
}

func (q *Queries) SetSubmissionHandled(ctx context.Context, arg SetSubmissionHandledParams) (Submission, error) {
	row := q.db.QueryRow(ctx, setSubmissionHandled, arg.SubmissionID, arg.Handled)
	var i Submission
	err := row.Scan(
		&i.SubmissionID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Kind,
		&i.Handled,
		&i.CreatedAt,
	)
	return i, err
}
