// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: videos.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (title, src, type, state_id, sublocation_id, status, about, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING video_id, title, src, type, slug, state_id, sublocation_id, status, about, created_by, created_at, updated_at
`

type CreateVideoParams struct {
	Title         string `json:"title"`
	Src           string `json:"src"`
	Type          string `json:"type"`
	StateID       int32  `json:"state_id"`
	SublocationID *int32 `json:"sublocation_id"`
	Status        string `json:"status"`
	About         string `json:"about"`
	CreatedBy     string `json:"created_by"`
}

type CreateVideoRow struct {
	VideoID       int32     `json:"video_id"`
	Title         string    `json:"title"`
	Src           string    `json:"src"`
	Type          string    `json:"type"`
	Slug          string    `json:"slug"`
	StateID       int32     `json:"state_id"`
	SublocationID *int32    `json:"sublocation_id"`
	Status        string    `json:"status"`
	About         string    `json:"about"`
	CreatedBy     string    `json:"created_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (CreateVideoRow, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.Title,
		arg.Src,
		arg.Type,
		arg.StateID,
		arg.SublocationID,
		arg.Status,
		arg.About,
		arg.CreatedBy,
	)
	var i CreateVideoRow
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Src,
		&i.Type,
		&i.Slug,
		&i.StateID,
		&i.SublocationID,
		&i.Status,
		&i.About,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos WHERE video_id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, videoID int32) error {
	_, err := q.db.Exec(ctx, deleteVideo, videoID)
	return err
}

const getPublicVideoSource = `-- name: GetPublicVideoSource :one
SELECT v.src
FROM videos v
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.video_id = $1
  AND v.status IN ('active', 'paused')
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
`

// GetPublicVideoSource backs the HLS proxy (DAN-241): the stored (raw) src of
// a camera that is publicly visible — same predicate as GetVideoBySlug — so a
// pending, inactive or rejected camera never streams. Returns no row otherwise.
func (q *Queries) GetPublicVideoSource(ctx context.Context, videoID int32) (string, error) {
	row := q.db.QueryRow(ctx, getPublicVideoSource, videoID)
	var src string
	err := row.Scan(&src)
	return src, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.about, v.owner_id, v.stream_id, v.review_note,
       v.created_by, v.created_at, v.updated_at,
       s.name AS state_name,
       COALESCE(sub.name, '') AS sublocation_name
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.video_id = $1
`

type GetVideoByIDRow struct {
	VideoID         int32       `json:"video_id"`
	Title           string      `json:"title"`
	Src             string      `json:"src"`
	Type            string      `json:"type"`
	Slug            string      `json:"slug"`
	StateID         int32       `json:"state_id"`
	SublocationID   *int32      `json:"sublocation_id"`
	Status          string      `json:"status"`
	About           string      `json:"about"`
	OwnerID         string      `json:"owner_id"`
	StreamID        pgtype.Text `json:"stream_id"`
	ReviewNote      string      `json:"review_note"`
	CreatedBy       string      `json:"created_by"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	StateName       string      `json:"state_name"`
	SublocationName string      `json:"sublocation_name"`
}

// GetVideoByID backs the admin create/update responses, so it returns any
// status and carries the ownership/review columns.
func (q *Queries) GetVideoByID(ctx context.Context, videoID int32) (GetVideoByIDRow, error) {
	row := q.db.QueryRow(ctx, getVideoByID, videoID)
	var i GetVideoByIDRow
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Src,
		&i.Type,
		&i.Slug,
		&i.StateID,
		&i.SublocationID,
		&i.Status,
		&i.About,
		&i.OwnerID,
		&i.StreamID,
		&i.ReviewNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.SublocationName,
	)
	return i, err
}

const getVideoBySlug = `-- name: GetVideoBySlug :one
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.view_count, v.about, v.created_by, v.created_at, v.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COALESCE(sub.name, '') AS sublocation_name,
       COALESCE(sub.slug, '') AS sublocation_slug
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.status IN ('active', 'paused')
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
  AND s.slug = $1
  AND COALESCE(sub.slug, '') = $2
  AND v.slug = $3
`

type GetVideoBySlugParams struct {
	StateSlug       string `json:"state_slug"`
	SublocationSlug string `json:"sublocation_slug"`
	Slug            string `json:"slug"`
}

type GetVideoBySlugRow struct {
	VideoID         int32     `json:"video_id"`
	Title           string    `json:"title"`
	Src             string    `json:"src"`
	Type            string    `json:"type"`
	Slug            string    `json:"slug"`
	StateID         int32     `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	Status          string    `json:"status"`
	ViewCount       int64     `json:"view_count"`
	About           string    `json:"about"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	StateSlug       string    `json:"state_slug"`
	SublocationName string    `json:"sublocation_name"`
	SublocationSlug string    `json:"sublocation_slug"`
}

// GetVideoBySlug backs the public per-camera page at
// /locations/{state_slug}/{sublocation_slug}/{slug}. Cameras with no sublocation
// match on an empty sublocation_slug.
func (q *Queries) GetVideoBySlug(ctx context.Context, arg GetVideoBySlugParams) (GetVideoBySlugRow, error) {
	row := q.db.QueryRow(ctx, getVideoBySlug, arg.StateSlug, arg.SublocationSlug, arg.Slug)
	var i GetVideoBySlugRow
	err := row.Scan(
		&i.VideoID,
		&i.Title,
		&i.Src,
		&i.Type,
		&i.Slug,
		&i.StateID,
		&i.SublocationID,
		&i.Status,
		&i.ViewCount,
		&i.About,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StateName,
		&i.StateSlug,
		&i.SublocationName,
		&i.SublocationSlug,
	)
	return i, err
}

const incrementVideoViews = `-- name: IncrementVideoViews :exec
UPDATE videos SET view_count = view_count + $2 WHERE video_id = $1
`

type IncrementVideoViewsParams struct {
	VideoID   int32 `json:"video_id"`
	ViewCount int64 `json:"view_count"`
}

func (q *Queries) IncrementVideoViews(ctx context.Context, arg IncrementVideoViewsParams) error {
	_, err := q.db.Exec(ctx, incrementVideoViews, arg.VideoID, arg.ViewCount)
	return err
}

const listArchiveSources = `-- name: ListArchiveSources :many
SELECT v.video_id, v.src
FROM videos v
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.status = 'active'
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
ORDER BY v.video_id
`

type ListArchiveSourcesRow struct {
	VideoID int32  `json:"video_id"`
	Src     string `json:"src"`
}

// ListArchiveSources is the snapshot archive's source list: active cameras
// only. Paused cameras are public (placeholder) but not capturing, and
// pending/rejected ones must not be archived at all.
func (q *Queries) ListArchiveSources(ctx context.Context) ([]ListArchiveSourcesRow, error) {
	rows, err := q.db.Query(ctx, listArchiveSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchiveSourcesRow{}
	for rows.Next() {
		var i ListArchiveSourcesRow
		if err := rows.Scan(&i.VideoID, &i.Src); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedVideos = `-- name: ListRelatedVideos :many
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.about, v.created_by, v.created_at, v.updated_at,
       s.name AS state_name, s.slug AS state_slug,
       COALESCE(sub.name, '') AS sublocation_name,
       COALESCE(sub.slug, '') AS sublocation_slug
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.status IN ('active', 'paused')
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
  AND v.video_id <> $1
  AND (v.sublocation_id = $2 OR v.state_id = $3)
ORDER BY (v.sublocation_id IS NOT DISTINCT FROM $2) DESC, v.title
LIMIT 6
`

type ListRelatedVideosParams struct {
	VideoID       int32  `json:"video_id"`
	SublocationID *int32 `json:"sublocation_id"`
	StateID       int32  `json:"state_id"`
}

type ListRelatedVideosRow struct {
	VideoID         int32     `json:"video_id"`
	Title           string    `json:"title"`
	Src             string    `json:"src"`
	Type            string    `json:"type"`
	Slug            string    `json:"slug"`
	StateID         int32     `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	Status          string    `json:"status"`
	About           string    `json:"about"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	StateSlug       string    `json:"state_slug"`
	SublocationName string    `json:"sublocation_name"`
	SublocationSlug string    `json:"sublocation_slug"`
}

// ListRelatedVideos returns other cameras to show alongside a camera page:
// same sublocation first, then the rest of the state.
func (q *Queries) ListRelatedVideos(ctx context.Context, arg ListRelatedVideosParams) ([]ListRelatedVideosRow, error) {
	rows, err := q.db.Query(ctx, listRelatedVideos, arg.VideoID, arg.SublocationID, arg.StateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedVideosRow{}
	for rows.Next() {
		var i ListRelatedVideosRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Src,
			&i.Type,
			&i.Slug,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.About,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.StateSlug,
			&i.SublocationName,
			&i.SublocationSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoSources = `-- name: ListVideoSources :many
SELECT DISTINCT src FROM videos
`

func (q *Queries) ListVideoSources(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listVideoSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var src string
		if err := rows.Scan(&src); err != nil {
			return nil, err
		}
		items = append(items, src)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many

SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.about, v.created_by, v.created_at, v.updated_at,
       s.name AS state_name,
       COALESCE(sub.name, '') AS sublocation_name
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.status IN ('active', 'paused')
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
ORDER BY v.title
`

type ListVideosRow struct {
	VideoID         int32     `json:"video_id"`
	Title           string    `json:"title"`
	Src             string    `json:"src"`
	Type            string    `json:"type"`
	Slug            string    `json:"slug"`
	StateID         int32     `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	Status          string    `json:"status"`
	About           string    `json:"about"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	SublocationName string    `json:"sublocation_name"`
}

// Public visibility (DAN-39): a camera is public when its status is 'active'
// or 'paused' (a paused camera renders a placeholder, DAN-40) AND its
// sublocation, if any, is 'approved'. Every query below that feeds a public
// endpoint — the lists (which also feed the sitemap and the search index),
// the per-camera page, related cameras, the popular/newest sorts, and via
// GetVideoBySlug the frames/snapshot/stream endpoints — applies the same
// predicate, so pending, inactive and rejected rows never leak.
func (q *Queries) ListVideos(ctx context.Context) ([]ListVideosRow, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosRow{}
	for rows.Next() {
		var i ListVideosRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Src,
			&i.Type,
			&i.Slug,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.About,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByCreated = `-- name: ListVideosByCreated :many
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.view_count, v.about, v.created_by, v.created_at, v.updated_at,
       s.name AS state_name,
       COALESCE(sub.name, '') AS sublocation_name
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.status IN ('active', 'paused')
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
ORDER BY v.created_at DESC, v.title
`

type ListVideosByCreatedRow struct {
	VideoID         int32     `json:"video_id"`
	Title           string    `json:"title"`
	Src             string    `json:"src"`
	Type            string    `json:"type"`
	Slug            string    `json:"slug"`
	StateID         int32     `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	Status          string    `json:"status"`
	ViewCount       int64     `json:"view_count"`
	About           string    `json:"about"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	SublocationName string    `json:"sublocation_name"`
}

// ListVideosByCreated backs GET /videos?sort=newest — the "Newest" ranking,
// ties broken by title so the order is stable.
func (q *Queries) ListVideosByCreated(ctx context.Context) ([]ListVideosByCreatedRow, error) {
	rows, err := q.db.Query(ctx, listVideosByCreated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosByCreatedRow{}
	for rows.Next() {
		var i ListVideosByCreatedRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Src,
			&i.Type,
			&i.Slug,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.ViewCount,
			&i.About,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByState = `-- name: ListVideosByState :many
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.about, v.created_by, v.created_at, v.updated_at,
       s.name AS state_name,
       COALESCE(sub.name, '') AS sublocation_name
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.state_id = $1
  AND v.status IN ('active', 'paused')
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
ORDER BY v.title
`

type ListVideosByStateRow struct {
	VideoID         int32     `json:"video_id"`
	Title           string    `json:"title"`
	Src             string    `json:"src"`
	Type            string    `json:"type"`
	Slug            string    `json:"slug"`
	StateID         int32     `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	Status          string    `json:"status"`
	About           string    `json:"about"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	SublocationName string    `json:"sublocation_name"`
}

func (q *Queries) ListVideosByState(ctx context.Context, stateID int32) ([]ListVideosByStateRow, error) {
	rows, err := q.db.Query(ctx, listVideosByState, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosByStateRow{}
	for rows.Next() {
		var i ListVideosByStateRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Src,
			&i.Type,
			&i.Slug,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.About,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosBySublocation = `-- name: ListVideosBySublocation :many
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.about, v.created_by, v.created_at, v.updated_at,
       s.name AS state_name,
       COALESCE(sub.name, '') AS sublocation_name
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.sublocation_id = $1
  AND v.status IN ('active', 'paused')
  AND sub.status = 'approved'
ORDER BY v.title
`

type ListVideosBySublocationRow struct {
	VideoID         int32     `json:"video_id"`
	Title           string    `json:"title"`
	Src             string    `json:"src"`
	Type            string    `json:"type"`
	Slug            string    `json:"slug"`
	StateID         int32     `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	Status          string    `json:"status"`
	About           string    `json:"about"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	SublocationName string    `json:"sublocation_name"`
}

func (q *Queries) ListVideosBySublocation(ctx context.Context, sublocationID *int32) ([]ListVideosBySublocationRow, error) {
	rows, err := q.db.Query(ctx, listVideosBySublocation, sublocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosBySublocationRow{}
	for rows.Next() {
		var i ListVideosBySublocationRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Src,
			&i.Type,
			&i.Slug,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.About,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByViews = `-- name: ListVideosByViews :many
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.view_count, v.about, v.created_by, v.created_at, v.updated_at,
       s.name AS state_name,
       COALESCE(sub.name, '') AS sublocation_name
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
WHERE v.status IN ('active', 'paused')
  AND (v.sublocation_id IS NULL OR sub.status = 'approved')
ORDER BY v.view_count DESC, v.title
`

type ListVideosByViewsRow struct {
	VideoID         int32     `json:"video_id"`
	Title           string    `json:"title"`
	Src             string    `json:"src"`
	Type            string    `json:"type"`
	Slug            string    `json:"slug"`
	StateID         int32     `json:"state_id"`
	SublocationID   *int32    `json:"sublocation_id"`
	Status          string    `json:"status"`
	ViewCount       int64     `json:"view_count"`
	About           string    `json:"about"`
	CreatedBy       string    `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	StateName       string    `json:"state_name"`
	SublocationName string    `json:"sublocation_name"`
}

// ListVideosByViews backs GET /videos?sort=views — the "Most watched" ranking,
// ties broken by title so the order is stable.
func (q *Queries) ListVideosByViews(ctx context.Context) ([]ListVideosByViewsRow, error) {
	rows, err := q.db.Query(ctx, listVideosByViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosByViewsRow{}
	for rows.Next() {
		var i ListVideosByViewsRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Src,
			&i.Type,
			&i.Slug,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.ViewCount,
			&i.About,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosPaginated = `-- name: ListVideosPaginated :many
SELECT v.video_id, v.title, v.src, v.type, v.slug, v.state_id, v.sublocation_id,
       v.status, v.about, v.owner_id, v.stream_id, v.review_note,
       v.created_by, v.created_at, v.updated_at,
       s.name AS state_name,
       COALESCE(sub.name, '') AS sublocation_name,
       COUNT(*) OVER()::int AS total_count
FROM videos v
JOIN states s ON s.state_id = v.state_id
LEFT JOIN sublocations sub ON sub.sublocation_id = v.sublocation_id
ORDER BY v.title
LIMIT $1 OFFSET $2
`

type ListVideosPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListVideosPaginatedRow struct {
	VideoID         int32       `json:"video_id"`
	Title           string      `json:"title"`
	Src             string      `json:"src"`
	Type            string      `json:"type"`
	Slug            string      `json:"slug"`
	StateID         int32       `json:"state_id"`
	SublocationID   *int32      `json:"sublocation_id"`
	Status          string      `json:"status"`
	About           string      `json:"about"`
	OwnerID         string      `json:"owner_id"`
	StreamID        pgtype.Text `json:"stream_id"`
	ReviewNote      string      `json:"review_note"`
	CreatedBy       string      `json:"created_by"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	StateName       string      `json:"state_name"`
	SublocationName string      `json:"sublocation_name"`
	TotalCount      int32       `json:"total_count"`
}

// ListVideosPaginated backs the admin dashboard, so it deliberately returns
// every status — filtering here made deactivated cameras unreachable from the
// dashboard with no way to reactivate them. Carries owner_id/stream_id/
// review_note so the admin console can tell owner-submitted cameras apart.
func (q *Queries) ListVideosPaginated(ctx context.Context, arg ListVideosPaginatedParams) ([]ListVideosPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listVideosPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosPaginatedRow{}
	for rows.Next() {
		var i ListVideosPaginatedRow
		if err := rows.Scan(
			&i.VideoID,
			&i.Title,
			&i.Src,
			&i.Type,
			&i.Slug,
			&i.StateID,
			&i.SublocationID,
			&i.Status,
			&i.About,
			&i.OwnerID,
			&i.StreamID,
			&i.ReviewNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StateName,
			&i.SublocationName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :exec
UPDATE videos SET title = $2, src = $3, type = $4, state_id = $5, sublocation_id = $6, status = $7, about = $8 WHERE video_id = $1
`

type UpdateVideoParams struct {
	VideoID       int32  `json:"video_id"`
	Title         string `json:"title"`
	Src           string `json:"src"`
	Type          string `json:"type"`
	StateID       int32  `json:"state_id"`
	SublocationID *int32 `json:"sublocation_id"`
	Status        string `json:"status"`
	About         string `json:"about"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) error {
	_, err := q.db.Exec(ctx, updateVideo,
		arg.VideoID,
		arg.Title,
		arg.Src,
		arg.Type,
		arg.StateID,
		arg.SublocationID,
		arg.Status,
		arg.About,
	)
	return err
}
