/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugIndexRouteImport } from './routes/locations/$slug.index'
import { Route as LocationsSlugSublocationSlugIndexRouteImport } from './routes/locations/$slug.$sublocationSlug.index'
import { Route as LocationsSlugSublocationSlugCameraSlugRouteImport } from './routes/locations/$slug.$sublocationSlug.$cameraSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugIndexRoute = LocationsSlugIndexRouteImport.update({
  id: '/locations/$slug/',
  path: '/locations/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugSublocationSlugIndexRoute =
  LocationsSlugSublocationSlugIndexRouteImport.update({
    id: '/locations/$slug/$sublocationSlug/',
    path: '/locations/$slug/$sublocationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsSlugSublocationSlugCameraSlugRoute =
  LocationsSlugSublocationSlugCameraSlugRouteImport.update({
    id: '/locations/$slug/$sublocationSlug/$cameraSlug',
    path: '/locations/$slug/$sublocationSlug/$cameraSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug': typeof LocationsSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/': typeof LocationsSlugSublocationSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/locations': typeof LocationsIndexRoute
  '/locations/$slug': typeof LocationsSlugIndexRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug': typeof LocationsSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug': typeof LocationsSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/': typeof LocationsSlugSublocationSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/$'
    | '/locations/'
    | '/locations/$slug/'
    | '/locations/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/$'
    | '/locations'
    | '/locations/$slug'
    | '/locations/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/sitemap.xml'
    | '/api/$'
    | '/locations/'
    | '/locations/$slug/'
    | '/locations/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CallbackRoute: typeof CallbackRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  LocationsSlugIndexRoute: typeof LocationsSlugIndexRoute
  LocationsSlugSublocationSlugCameraSlugRoute: typeof LocationsSlugSublocationSlugCameraSlugRoute
  LocationsSlugSublocationSlugIndexRoute: typeof LocationsSlugSublocationSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/': {
      id: '/locations/$slug/'
      path: '/locations/$slug'
      fullPath: '/locations/$slug/'
      preLoaderRoute: typeof LocationsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug/': {
      id: '/locations/$slug/$sublocationSlug/'
      path: '/locations/$slug/$sublocationSlug'
      fullPath: '/locations/$slug/$sublocationSlug/'
      preLoaderRoute: typeof LocationsSlugSublocationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug/$cameraSlug': {
      id: '/locations/$slug/$sublocationSlug/$cameraSlug'
      path: '/locations/$slug/$sublocationSlug/$cameraSlug'
      fullPath: '/locations/$slug/$sublocationSlug/$cameraSlug'
      preLoaderRoute: typeof LocationsSlugSublocationSlugCameraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CallbackRoute: CallbackRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  LocationsSlugIndexRoute: LocationsSlugIndexRoute,
  LocationsSlugSublocationSlugCameraSlugRoute:
    LocationsSlugSublocationSlugCameraSlugRoute,
  LocationsSlugSublocationSlugIndexRoute:
    LocationsSlugSublocationSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
