/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as CamerasNewRouteImport } from './routes/cameras.new'
import { Route as CamerasPopularRouteImport } from './routes/cameras.popular'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'
import { Route as LocationsSlugIndexRouteImport } from './routes/locations/$slug.index'
import { Route as EmbedSlugSublocationSlugCameraSlugRouteImport } from './routes/embed.$slug.$sublocationSlug.$cameraSlug'
import { Route as LocationsSlugSublocationSlugIndexRouteImport } from './routes/locations/$slug.$sublocationSlug.index'
import { Route as LocationsSlugSublocationSlugCameraSlugRouteImport } from './routes/locations/$slug.$sublocationSlug.$cameraSlug'
import { Route as LocationsSlugSublocationSlugConditionsRouteImport } from './routes/locations/$slug.$sublocationSlug.conditions'
import { Route as LocationsSlugSublocationSlugCameraSlugArchiveRouteImport } from './routes/locations/$slug.$sublocationSlug.$cameraSlug_.archive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasNewRoute = CamerasNewRouteImport.update({
  id: '/cameras/new',
  path: '/cameras/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasPopularRoute = CamerasPopularRouteImport.update({
  id: '/cameras/popular',
  path: '/cameras/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugIndexRoute = LocationsSlugIndexRouteImport.update({
  id: '/locations/$slug/',
  path: '/locations/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSlugSublocationSlugCameraSlugRoute =
  EmbedSlugSublocationSlugCameraSlugRouteImport.update({
    id: '/embed/$slug/$sublocationSlug/$cameraSlug',
    path: '/embed/$slug/$sublocationSlug/$cameraSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsSlugSublocationSlugIndexRoute =
  LocationsSlugSublocationSlugIndexRouteImport.update({
    id: '/locations/$slug/$sublocationSlug/',
    path: '/locations/$slug/$sublocationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsSlugSublocationSlugCameraSlugRoute =
  LocationsSlugSublocationSlugCameraSlugRouteImport.update({
    id: '/locations/$slug/$sublocationSlug/$cameraSlug',
    path: '/locations/$slug/$sublocationSlug/$cameraSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsSlugSublocationSlugConditionsRoute =
  LocationsSlugSublocationSlugConditionsRouteImport.update({
    id: '/locations/$slug/$sublocationSlug/conditions',
    path: '/locations/$slug/$sublocationSlug/conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsSlugSublocationSlugCameraSlugArchiveRoute =
  LocationsSlugSublocationSlugCameraSlugArchiveRouteImport.update({
    id: '/locations/$slug/$sublocationSlug/$cameraSlug_/archive',
    path: '/locations/$slug/$sublocationSlug/$cameraSlug/archive',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/cameras/new': typeof CamerasNewRoute
  '/cameras/popular': typeof CamerasPopularRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/locations/': typeof LocationsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
  '/embed/$slug/$sublocationSlug/$cameraSlug': typeof EmbedSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug': typeof LocationsSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/conditions': typeof LocationsSlugSublocationSlugConditionsRoute
  '/locations/$slug/$sublocationSlug/': typeof LocationsSlugSublocationSlugIndexRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug/archive': typeof LocationsSlugSublocationSlugCameraSlugArchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/cameras/new': typeof CamerasNewRoute
  '/cameras/popular': typeof CamerasPopularRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/locations': typeof LocationsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/locations/$slug': typeof LocationsSlugIndexRoute
  '/embed/$slug/$sublocationSlug/$cameraSlug': typeof EmbedSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug': typeof LocationsSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/conditions': typeof LocationsSlugSublocationSlugConditionsRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugIndexRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug/archive': typeof LocationsSlugSublocationSlugCameraSlugArchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/callback': typeof CallbackRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/$': typeof ApiSplatRoute
  '/cameras/new': typeof CamerasNewRoute
  '/cameras/popular': typeof CamerasPopularRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/locations/': typeof LocationsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
  '/embed/$slug/$sublocationSlug/$cameraSlug': typeof EmbedSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug': typeof LocationsSlugSublocationSlugCameraSlugRoute
  '/locations/$slug/$sublocationSlug/conditions': typeof LocationsSlugSublocationSlugConditionsRoute
  '/locations/$slug/$sublocationSlug/': typeof LocationsSlugSublocationSlugIndexRoute
  '/locations/$slug/$sublocationSlug/$cameraSlug_/archive': typeof LocationsSlugSublocationSlugCameraSlugArchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/$'
    | '/cameras/new'
    | '/cameras/popular'
    | '/notes/$slug'
    | '/locations/'
    | '/notes/'
    | '/locations/$slug/'
    | '/embed/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/conditions'
    | '/locations/$slug/$sublocationSlug/'
    | '/locations/$slug/$sublocationSlug/$cameraSlug/archive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/$'
    | '/cameras/new'
    | '/cameras/popular'
    | '/notes/$slug'
    | '/locations'
    | '/notes'
    | '/locations/$slug'
    | '/embed/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/conditions'
    | '/locations/$slug/$sublocationSlug'
    | '/locations/$slug/$sublocationSlug/$cameraSlug/archive'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/callback'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/$'
    | '/cameras/new'
    | '/cameras/popular'
    | '/notes/$slug'
    | '/locations/'
    | '/notes/'
    | '/locations/$slug/'
    | '/embed/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/$cameraSlug'
    | '/locations/$slug/$sublocationSlug/conditions'
    | '/locations/$slug/$sublocationSlug/'
    | '/locations/$slug/$sublocationSlug/$cameraSlug_/archive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CallbackRoute: typeof CallbackRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CamerasNewRoute: typeof CamerasNewRoute
  CamerasPopularRoute: typeof CamerasPopularRoute
  NotesSlugRoute: typeof NotesSlugRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  LocationsSlugIndexRoute: typeof LocationsSlugIndexRoute
  EmbedSlugSublocationSlugCameraSlugRoute: typeof EmbedSlugSublocationSlugCameraSlugRoute
  LocationsSlugSublocationSlugCameraSlugRoute: typeof LocationsSlugSublocationSlugCameraSlugRoute
  LocationsSlugSublocationSlugConditionsRoute: typeof LocationsSlugSublocationSlugConditionsRoute
  LocationsSlugSublocationSlugIndexRoute: typeof LocationsSlugSublocationSlugIndexRoute
  LocationsSlugSublocationSlugCameraSlugArchiveRoute: typeof LocationsSlugSublocationSlugCameraSlugArchiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/new': {
      id: '/cameras/new'
      path: '/cameras/new'
      fullPath: '/cameras/new'
      preLoaderRoute: typeof CamerasNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/popular': {
      id: '/cameras/popular'
      path: '/cameras/popular'
      fullPath: '/cameras/popular'
      preLoaderRoute: typeof CamerasPopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/': {
      id: '/locations/$slug/'
      path: '/locations/$slug'
      fullPath: '/locations/$slug/'
      preLoaderRoute: typeof LocationsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$slug/$sublocationSlug/$cameraSlug': {
      id: '/embed/$slug/$sublocationSlug/$cameraSlug'
      path: '/embed/$slug/$sublocationSlug/$cameraSlug'
      fullPath: '/embed/$slug/$sublocationSlug/$cameraSlug'
      preLoaderRoute: typeof EmbedSlugSublocationSlugCameraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug/': {
      id: '/locations/$slug/$sublocationSlug/'
      path: '/locations/$slug/$sublocationSlug'
      fullPath: '/locations/$slug/$sublocationSlug/'
      preLoaderRoute: typeof LocationsSlugSublocationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug/$cameraSlug': {
      id: '/locations/$slug/$sublocationSlug/$cameraSlug'
      path: '/locations/$slug/$sublocationSlug/$cameraSlug'
      fullPath: '/locations/$slug/$sublocationSlug/$cameraSlug'
      preLoaderRoute: typeof LocationsSlugSublocationSlugCameraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug/conditions': {
      id: '/locations/$slug/$sublocationSlug/conditions'
      path: '/locations/$slug/$sublocationSlug/conditions'
      fullPath: '/locations/$slug/$sublocationSlug/conditions'
      preLoaderRoute: typeof LocationsSlugSublocationSlugConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug/$cameraSlug_/archive': {
      id: '/locations/$slug/$sublocationSlug/$cameraSlug_/archive'
      path: '/locations/$slug/$sublocationSlug/$cameraSlug/archive'
      fullPath: '/locations/$slug/$sublocationSlug/$cameraSlug/archive'
      preLoaderRoute: typeof LocationsSlugSublocationSlugCameraSlugArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CallbackRoute: CallbackRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiSplatRoute: ApiSplatRoute,
  CamerasNewRoute: CamerasNewRoute,
  CamerasPopularRoute: CamerasPopularRoute,
  NotesSlugRoute: NotesSlugRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  LocationsSlugIndexRoute: LocationsSlugIndexRoute,
  EmbedSlugSublocationSlugCameraSlugRoute:
    EmbedSlugSublocationSlugCameraSlugRoute,
  LocationsSlugSublocationSlugCameraSlugRoute:
    LocationsSlugSublocationSlugCameraSlugRoute,
  LocationsSlugSublocationSlugConditionsRoute:
    LocationsSlugSublocationSlugConditionsRoute,
  LocationsSlugSublocationSlugIndexRoute:
    LocationsSlugSublocationSlugIndexRoute,
  LocationsSlugSublocationSlugCameraSlugArchiveRoute:
    LocationsSlugSublocationSlugCameraSlugArchiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
