/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsSlugIndexRouteImport } from './routes/locations/$slug.index'
import { Route as LocationsSlugSublocationSlugRouteImport } from './routes/locations/$slug.$sublocationSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugIndexRoute = LocationsSlugIndexRouteImport.update({
  id: '/locations/$slug/',
  path: '/locations/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugSublocationSlugRoute =
  LocationsSlugSublocationSlugRouteImport.update({
    id: '/locations/$slug/$sublocationSlug',
    path: '/locations/$slug/$sublocationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/locations': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
  '/locations/$slug': typeof LocationsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/locations/': typeof LocationsIndexRoute
  '/locations/$slug/$sublocationSlug': typeof LocationsSlugSublocationSlugRoute
  '/locations/$slug/': typeof LocationsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/sitemap.xml'
    | '/locations/'
    | '/locations/$slug/$sublocationSlug'
    | '/locations/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/sitemap.xml'
    | '/locations'
    | '/locations/$slug/$sublocationSlug'
    | '/locations/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/sitemap.xml'
    | '/locations/'
    | '/locations/$slug/$sublocationSlug'
    | '/locations/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  LocationsSlugSublocationSlugRoute: typeof LocationsSlugSublocationSlugRoute
  LocationsSlugIndexRoute: typeof LocationsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/': {
      id: '/locations/$slug/'
      path: '/locations/$slug'
      fullPath: '/locations/$slug/'
      preLoaderRoute: typeof LocationsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug/$sublocationSlug': {
      id: '/locations/$slug/$sublocationSlug'
      path: '/locations/$slug/$sublocationSlug'
      fullPath: '/locations/$slug/$sublocationSlug'
      preLoaderRoute: typeof LocationsSlugSublocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  LocationsSlugSublocationSlugRoute: LocationsSlugSublocationSlugRoute,
  LocationsSlugIndexRoute: LocationsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
